### ISSUE TITLE
Unable to get property 'id' of undefined or null reference

### ISSUE THREAD

**Issue by DeepalihDanokar** [KasperOlesen/DataTable-AltEditor#10]
I am getting this js error while editing the record on following line:

**ERROR** : Unable to get property 'id' of undefined or null reference
**CODE**:
 //Adding the inputs from the edit-modal
        for(var i = 0; i < dataSet.length; i++){
         jsonDataArray[columnIds[i+1].id] = dataSet[i];
        //  rowDataArray[columnIds[i+1].id] = dataSet[i];
        }

Why id is getting null ref ?

**Comment by luca-vercelli** [comment]
Closing, refers to outdated code
