### ISSUE TITLE
Is there a way to render my own input field for each property of the object?

### ISSUE THREAD

**Issue by JulioPablo** [KasperOlesen/DataTable-AltEditor#103]
Hi, 

I'm wondering if there is a way for me to provide a custom render function or something, to render a input field? Mainly asking for custom inputs, like formatted texts or other custom scenrios.

Also wondering if async validation is available? Say for example to update a email address, so that it could be checked that the new address is not already present.

Regards.

**Comment by luca-vercelli** [comment]
> I'm wondering if there is a way for me to provide a custom render function or something, to render a input field? Mainly asking for custom inputs, like formatted texts or other custom scenrios.

No, there is nothing as such so far.


> Also wondering if async validation is available? Say for example to update a email address, so that it could be checked that the new address is not already present.

No, there is not async validation (at least I think). You can only check the fields when the user saves the data and submits to the server.

**Comment by JulioPablo** [comment]
Gotcha. Thanks for the answer.
