### ISSUE TITLE
Json Array

### ISSUE THREAD

**Issue by inihaekal** [KasperOlesen/DataTable-AltEditor#106]
Hi Kasper,

Thank you for your awesome script,
do you have any example of how to read JSON Array with alteditor to use get, post,put, delete features?
please I'm stuck here :(

Thanks !

**Comment by luca-vercelli** [comment]
Hi,
what do you mean with "JSON Array" here? What's your JSON like?

**Comment by inihaekal** [comment]
Hi @luca-vercelli , Thanks for your response :) .

I had JSON like this 
`{
   "data":[
      [
         1,
         "Default",
         "Default Profile"
      ],
      [
         4,
         "koneksi 2",
         "des"
      ],
      [
         5,
         "inventory 5",
         "deksripsi"
      ],
      [
         6,
         "test123",
         "descsssss"
      ],
      [
         7,
         "wewewewe",
         "3232323"
      ]
   ],
   "draw":1,
   "recordsFiltered":5,
   "recordsTotal":5
}`

I have no idea how to call this one into alteditor, i tried to write like this, but i had a problem to edit and delete this .
` var columnCategory = [{
            title: "ID",
            type: "readonly",
            data: "0"
            
           
          }, {
            title: "Name",
            data: "1"
          }, {
            title: "Description",
            type:"textarea",
            data: "2"
          }];`

**Comment by luca-vercelli** [comment]
I don't think this situation has ever been tested...
I cannot even imagine how your table looks like!

**Comment by inihaekal** [comment]
got the issue like this https://github.com/KasperOlesen/DataTable-AltEditor/issues/5

is there any way to set data properly for JSON like that  ?

**Comment by luca-vercelli** [comment]
Can you please paste a screenshot of yuou Datatable? Really, I cannot imagine how it looks like.

**Comment by inihaekal** [comment]
Really,im so sorry for ur confusing, regarding getting value from the array now is successful as im follow from example1.

now I have a problem when I want to delete or edit the data without a key from JSON like this :
`{"data":[[5,"inventory 5","deksripsi"],[6,"test123","descsssss"],[7,"wewewewe","3232323"]]}`

```
var url_delete = /admin/inventory/profile/delete?" + "id=" +**id**+ "&"+ "csrf_token=" + csrf_token;
```

i have delete method here using ajax:

`      onDeleteRow: function(datatable, rowdata, success, error) {
          $.ajax({
              url: url_delete,
              type: 'GET',
              data: rowdata,
              success: success,
              error: error,
          });
      }`

the question is, how to set dynamically **id** in URL get from selected row array[1] ?

**Comment by luca-vercelli** [comment]
Inside your `function`, before calling `$.ajax`, you can read the `rowdata` argument, you should see the whole selected line, so you can compose your url.

**Comment by inihaekal** [comment]
@luca-vercelli I'm so sorry I didn't get you.
can you please give me 1 simple example?

**Comment by inihaekal** [comment]
I tried to change this one, but I don't know why it's working.
![image](https://user-images.githubusercontent.com/62714156/81898157-53d77c80-95e2-11ea-8fe1-76be299058bb.png)
thanks !!!
