### ISSUE TITLE
Length Menu

### ISSUE THREAD

**Issue by instantham** [KasperOlesen/DataTable-AltEditor#107]
Hi, i don't really good at all of this so just quick question,
is there anyway to show the original Length Menu of Datatable since The button editor replace it.
Thank you

**Comment by luca-vercelli** [comment]
You can try playing with the [dom](https://datatables.net/reference/option/dom) property, for example `dom='Bfrtilp'`

**Comment by instantham** [comment]
Ah right was searching that for hours.... I should read the documentation more... 🤦
Thank you very much it works like a charm@
