### ISSUE TITLE
hide value on delete

### ISSUE THREAD

**Issue by inihaekal** [KasperOlesen/DataTable-AltEditor#108]
Hi, Thanks for the awesome script,

is it possible to hide value from delete modal ? 
![image](https://user-images.githubusercontent.com/62714156/82070574-26342580-96ff-11ea-9f66-af7d61b012fa.png)

**Comment by luca-vercelli** [comment]
I think you should catch the `alteditor:delete_dialog_opened` event, and in that case you can execute some jquery code that hides the input field, something like `$('#mypassword').hide()` .

**Comment by nauman22** [comment]
Please give us a simple example for this issue.

**Comment by luca-vercelli** [comment]
I found something similar in issue #49.

If `mytable` is the id of your datatable, and `password` is the id of your attribute, you can try this:

```
  $(document).on("alteditor:delete_dialog_opened", function(evt){
      var modal_selector = $('#mytable')[0].altEditor.modal_selector;
      $(modal_selector).find("#password").closest("div").hide();
  });
```

**Comment by nauman22** [comment]
thank you

**Comment by Sebas1245** [comment]
Hi, I'm trying to use the example you provided here but it isn't working. It's not catching the event at all,  but I'm using version 3.0 that comes with SmartAdmin template and I noticed that the repo src says its version 2.0, would that be a reason for this not working?

**Comment by luca-vercelli** [comment]
@Sebas1245 what version are you talking about? jquery 3.0 is supported
