### ISSUE TITLE
chrome error edit error - null on line 294 (resolved for myself, not others)

### ISSUE THREAD

**Issue by Cobwebster** [KasperOlesen/DataTable-AltEditor#109]
When attempting to edit a row,

dataTables.altEditor.free.js:294 Uncaught TypeError: Cannot read property 'toString' of null
    at altEditor._openEditModal (dataTables.altEditor.free.js:294)
    at x.<anonymous> (dataTables.altEditor.free.js:188)
    at k (dataTables.buttons.min.js:14)
    at HTMLAnchorElement.<anonymous> (dataTables.buttons.min.js:15)
    at HTMLAnchorElement.dispatch (jquery-3.5.1.js:5429)
    at HTMLAnchorElement.elemData.handle (jquery-3.5.1.js:5233)

When selecting a row it doesn't grab the data and once i finish my edit it'll just add a new row instead of updating.

I fixed this on my end by wrapping a if check on columnDefs[j].name, might be worth adding to the project. line 294

**Comment by luca-vercelli** [comment]
Thank you for your report.

So, in your case, `columnDefs[j].name` was null? I didn't imagine that was possible.
That column arrives from JSON, or is it calculated by some function?

And, are your rows represented by objects or by arrays?

**Comment by Cobwebster** [comment]
> Thank you for your report.
> 
> So, in your case, `columnDefs[j].name` was null? I didn't imagine that was possible.
> That column arrives from JSON, or is it calculated by some function?
> 
> And, are your rows represented by objects or by arrays?

Our data consists of array'd objects, our columnDef is like this,

`
 var columnDefs = [
            {
                "className":      'details-control',
                "orderable":      false,
                "data":           null,
                "defaultContent": ''
            },
            {
              data: "_id",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "put_up",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "subgenre",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "take_down",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "platforms",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "errors",
              defaultContent: "<i>No Errors Found</i>",
            },
            {
              data: "parental_guidance",
              defaultContent: "<i>Not set</i>",
            },
            {
              data: "production_company_location",
              defaultContent: "<i>Not set</i>",
            },
          ]
`

**Comment by luca-vercelli** [comment]
Yes, I think it could be the first column. I shall see.
