### ISSUE TITLE
checkboxes dont work

### ISSUE THREAD

**Issue by mjbernot** [KasperOlesen/DataTable-AltEditor#112]
Hi Checkboxes don't seem to work with boolean values.
I have tried using strings with a value of "on" and "checked" neither seem to work.

Will work on a pull request.

**Comment by luca-vercelli** [comment]
Hello, checkboxes are not currently supported. Thank you if you want work on this.

**Comment by mjbernot** [comment]
ok thanks for the confirmation, i'll add this.

**Comment by mjbernot** [comment]
@luca-vercelli what is your thoughts on having moment as a requirement for formatting dates?

**Comment by luca-vercelli** [comment]
@mjbernot I think it's ok, provided that the library is optional.
If a user does not need to format dates, he must not be obliged to install moment.js.

P.S. is this related to issue #114 ?

**Comment by mjbernot** [comment]
awesome thanks!
