### ISSUE TITLE
Time input in seconds

### ISSUE THREAD

**Issue by PixelDonut** [KasperOlesen/DataTable-AltEditor#114]
In the modal I would like to have a time input field with the format hh:mm:ss. But I can't get this to work. Am i looking over someting?

**Comment by luca-vercelli** [comment]
did you try the datetimepicker?

**Comment by PixelDonut** [comment]
Yes I did try it but it looks like a normal textfield and there is no popup. With the time input there is a popup to set the time.

**Comment by luca-vercelli** [comment]
This is quite an old question, but I think that `type="time"` may give what you want. Not working in IE, of course.
