### ISSUE TITLE
Null fields rendered as undefined

### ISSUE THREAD

**Issue by Enkidu82** [KasperOlesen/DataTable-AltEditor#12]
Null fields are rendered as undefined string in the editor window and this behavior is not desirable for users.
In addition, this can cause parsing error while editing when mapping the json object to the model by Spring controller in case of non string values.

**Comment by luca-vercelli** [comment]
> Null fields are rendered as undefined string in the editor window
To be more precise, null fields are rendered as "null" (not "undefined")

**Comment by luca-vercelli** [comment]
I didn't noticed this anymore
