### ISSUE TITLE
Hide column in modal for Add & Edit

### ISSUE THREAD

**Issue by shariful2011** [KasperOlesen/DataTable-AltEditor#120]
How can I hide some columns of table in the modal? Please help.

**Comment by luca-vercelli** [comment]
There is nothing specific for this purpose.
You can see a workaround in issue #108

**Comment by MuhmdRaouf** [comment]
Hey guys I know this is super late, but oh well it might help other people in the future too
the solution that worked for me was using `type: 'hidden'` in the ColumnDef as @luca-vercelli suggested in that comment
https://github.com/KasperOlesen/DataTable-AltEditor/issues/65#issuecomment-552402531 it works like a charm for me.
