### ISSUE TITLE
question about single and double quotes in select

### ISSUE THREAD

**Issue by mjbernot** [KasperOlesen/DataTable-AltEditor#121]
hi @luca-vercelli question, 
If you have a single or double quote in select options, the edit dialog doesn't select that row.

if you change line 298 from
`$(selector).find(jquerySelector).val(this._quoteattr(selectedValue));`
to 
`$(selector).find(jquerySelector).val(selectedValue);`
then it works correctly.

What is this "_quoteattr" method needed for?

thanks

**Comment by luca-vercelli** [comment]
This is an interesting question. Can you please provide an example where you need this modification?

**Comment by mjbernot** [comment]
Hi this is what I have seen with a before and after:
![Untitled](https://user-images.githubusercontent.com/27690461/85137913-ed143700-b20f-11ea-9b74-1923f59bb382.png)

**Comment by luca-vercelli** [comment]
I cannot understand yet.
At line https://github.com/KasperOlesen/DataTable-AltEditor/blob/4589c7c90dae80cb25a55d6c664cb8e09eae0b07/src/dataTables.altEditor.free.js#L585
the option value is sanitized, so I think it should be sanitized also here https://github.com/KasperOlesen/DataTable-AltEditor/blob/4589c7c90dae80cb25a55d6c664cb8e09eae0b07/src/dataTables.altEditor.free.js#L298
Am I wrong? What is the difference?

**Comment by mjbernot** [comment]
Hi @luca-vercelli sorry if I didn't explain this well.
Its only when using double or single quotes in a field when its selected as a value (only on edit screen), that it seems to be an issue.
Line 585 makes sense as they need to be sanitized before being added as an option in the html itself.

if you save a single or double quote as text it will be displayed as the HTML equivalent &apos; or &quot;
(see image before change)

and I think you would want it to display like the after change image, as end users wont understand what &apos; or &quot; even means.

please let me know if you need more info. thanks

**Comment by luca-vercelli** [comment]
I did the change that you proposed. I am not sure yet of possible problems this can create.

**Comment by mjbernot** [comment]
ok thanks
