### ISSUE TITLE
Only these Datatables and Bootstrap versions are supported

### ISSUE THREAD

**Issue by rafaelsanchezrd** [KasperOlesen/DataTable-AltEditor#122]
Hello, I had a hard time trying to get the plugin working with other libraries versions than the followings:
<script src="https://code.jquery.com/jquery-1.12.4.js" ></script>
<script src="https://cdn.datatables.net/1.10.11/js/jquery.dataTables.js" ></script>
<script src="https://cdn.datatables.net/buttons/1.1.2/js/dataTables.buttons.js" ></script>
<script src="https://cdn.datatables.net/select/1.1.2/js/dataTables.select.js" ></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.js" ></script>
<script src="https://cdn.datatables.net/responsive/2.0.2/js/dataTables.responsive.js" ></script>
Especially Boostrap.

I was implementing the plugins that come with AdminLTE admin Dashboard and none works, the buttons do not display the models when using any other version.

how can I help?

**Comment by luca-vercelli** [comment]
can you provide some js fiddle?

**Comment by luca-vercelli** [comment]
The versions of the dependencies now changed.
