### ISSUE TITLE
Undefined in  _editRowData

### ISSUE THREAD

**Issue by rafaelsanchezrd** [KasperOlesen/DataTable-AltEditor#123]
I'm having trouble trying to send the data to server I can see the object but is undefined, is there ea fix for this bug?

I also notice that there is DEBUG comment in  console.log(rowDataArray); //DEBUG

                var checkFilesQueued = function() {
                    if (numFilesQueued == 0) {
                        that.onEditRow(that,
                            rowDataArray,
                            function(data,b,c,d,e){ that._editRowCallback(data,b,c,d,e); },
                            function(data){ that._errorCallback(data);
                        });
                    } else {
                        console.log("Waiting for file base64-decoding...");
                        setTimeout(checkFilesQueued, 1000);
                    }
                };

Any help?

**Comment by luca-vercelli** [comment]
Can you please better explain your error? what is undefined?

**Comment by rafaelsanchezrd** [comment]
Sure and thanks for responding

Here is the  Js I'm using for the actions, I'm working with edit part
[proposal.txt](https://github.com/KasperOlesen/DataTable-AltEditor/files/4792116/proposal.txt)

Here is the capture of the results I see in the console when hitting in Edit in the modal.

![console Capture](https://user-images.githubusercontent.com/5248544/84892429-90781700-b06b-11ea-95e7-35a3ad15e65b.PNG)


Here I the edit function in my code, the parameter _datatable_ in the function I don't understand well how to use it.

`        onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                // a tipycal url would be /{id} with type='POST'
                url: 'https://stg-albeeassociates.herokuapp.com/user/edit_proposal/1',
                type: 'POST',
                data: rowdata,
                success: function() { 
                    console.log("Data sent to the server: \n\n "+rowdata);
                    console.log("Data recieved from the server: \n\n Success: "+rowdata);
                    console.log("Mensaje de Success: "+success);
                },
                error: function() {
                console.log('Error....'+error);
        }
            });
        }`

**Comment by rafaelsanchezrd** [comment]
I think I got it working but still the undefined is there I changed the onEditRow function to this:

`     onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                // a tipycal url would be /{id} with type='POST'
                url: 'https://stg-albeeassociates.herokuapp.com/user/edit_proposal/1',
                type: 'POST',
                data: {myData:rowdata},
                success: function(data) { 
                    console.log("Data sent to the server: \n\n "+JSON.stringify(rowdata));
                    console.log("Data recieved from the server: \n\n Success: "+data);
                    console.log("Mensaje de Success: "+success);
                },
                error: function() {
                console.log('Error....'+error);
        }
            });
        }`

**Comment by rafaelsanchezrd** [comment]
The only thing I notice is that when the edit button is clicked and the update is processed the feedback is not showing in the modal Window.

**Comment by luca-vercelli** [comment]
what if you remove the "mRender" column? is the "undefined" still there?

**Comment by rafaelsanchezrd** [comment]
Hello I clean-up de code and now is OK, but I don't see the Success! message once I update the record and it gets updated.

`
$(document).ready(function() {

    var columnDefs = [
     {
        data: "Id",
        title: "Id",
        type: "readonly",
        "visible": false,
        "searchable": false
      },
     {
        data: "Name",
        title: "Name"
      },
     {
        data: "McLabs2__Status__c",
        title: "Pipeline Status",
        "defaultContent": "",
        type : "select",
        options : [
            "Waiting on Form/DS",
            "No-Cost Estimate",
            "Adjusting Analysis",
            "Waiting on CPA",
            "In Process",
            "Closed Lost Business",
            "Close Won Business",
            "Follow-Up",
            "Scheduling",
            "Send Back",
            "Dead Lead"
        ]
    },
     {
        data: "RecordType.Name",
        title: "Recrod Type"
      },
     {
        data: "McLabs2__Client_Company__r.Name",
        title: "Company",
        "defaultContent": ""
      },
     {
        data: "McLabs2__Client__r.Name",
        title: "Contact",
        "defaultContent": ""
      },
     {
        data: "McLabs2__Client__r.Email",
        title: "Email",
        "defaultContent": ""
      },
     {
        data: "McLabs2__Client__r.MobilePhone",
        title: "Phone",
        "defaultContent": ""
      },
     {
        data: "CreatedDate",
        title: "Created Date",
        type: "readonly"
      },
     {
        data: "LastActivityDate",
        title: "LastActivity Date",
        type: "readonly",
        "defaultContent": ""
      },
     {
        data: "LastModifiedDate",
        title: "Last Modified",
        type: "readonly",
        "defaultContent": ""
      }
      ];
  
  
  var myTable;
  
  myTable = $('#proposal_table').DataTable({
        "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
        "order": [[ 3, "desc" ]],
        "sPaginationType": "full_numbers",
    ajax: {
        url : 'proposal/ajax_proposal_call',
        // our data is an array of objects, in the root node instead of /data node, so we need 'dataSrc' parameter
        dataSrc : ''
    },
    columns: columnDefs,
	dom: 'Bfrtip',        // Needs button container
        select: 'single',
        responsive: true,
        altEditor: true,     // Enable altEditor
        buttons: [{
            text: 'Add',
            name: 'add'        // do not change name
        },
        {
            extend: 'selected', // Bind to Selected row
            text: 'Edit',
            name: 'edit'        // do not change name
        },
//        {
//            extend: 'selected', // Bind to Selected row
//            text: 'Delete',
//            name: 'delete'      // do not change name
//        },
        {
            text: 'Refresh',
            name: 'refresh'      // do not change name
        }],
        onAddRow: function(datatable, rowdata, success, error) {
            $.ajax({
                // a tipycal url would be / with type='PUT'
                url: 'proposal/edit_proposal',
                type: 'POST',
                data: rowdata,
                success: success,
                error: error
            });
        },
//        onDeleteRow: function(datatable, rowdata, success, error) {
//         
////            $.ajax({
////                // a tipycal url would be /{id} with type='DELETE'
////                url: url_ws_mock_ok,
////                type: 'GET',
////                data: rowdata,
////                success: success,
////                error: error
////            });
//        },
        onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                // a tipycal url would be /{id} with type='POST'
                url: 'https://stg-albeeassociates.herokuapp.com/user/edit_proposal/1',
                type: 'POST',
                data: {myData:rowdata},
                success: success,
                error: error
//                success: function(data) { 
//                    console.log("Data sent to the server: \n\n "+JSON.stringify(rowdata));
//                    console.log("Data recieved from the server: \n\n Success: "+data);
//                    console.log("Mensaje de Success: "+success);
//                },
//                error: function() {
//                console.log('Error....'+error);
//        }
            });
        }
  });


});`

**Comment by rafaelsanchezrd** [comment]
the code above should work
