### ISSUE TITLE
General Question: Is possible to add custom buttons?

### ISSUE THREAD

**Issue by rafaelsanchezrd** [KasperOlesen/DataTable-AltEditor#124]
I see the buttons:  Add. Edit, Delete, Refresh and a comment  saying  // do not change name

is it possible to add custom buttons with any other name we want?

I know this is a Datatables feature but could this mess this plugin if I add buttons to each row?

**Comment by luca-vercelli** [comment]
If you mean to add other buttons more than "Add", Edit", "Delete" over the table: yes, there is no problem. Please just don't change the "name" if the 3 buttons above.

If you mean to add buttons "inline" on each row: this is more problematic. I don't know.

**Comment by rafaelsanchezrd** [comment]
Mmm, but how to fire a function with a custom button?

**Comment by luca-vercelli** [comment]
what kind of function are you thinking of?
and, is this question related with altEditor, or is this a question on datatables? buttons are a standard component, see e.g. [the docs](https://datatables.net/extensions/buttons/)

**Comment by rafaelsanchezrd** [comment]
is related to AltEditor, we have the basic CRUD in AltEditor, but you could have a scenario like mine where you add a sub-table and you could take action on sub-table but need the Id from the parent, it's like put AltEditor in a subtable..

An image can speak more I put an image here

![image](https://user-images.githubusercontent.com/5248544/85632903-2f8da780-b646-11ea-85ca-d99ffc5c31ea.png)

**Comment by luca-vercelli** [comment]
Please see https://luca-vercelli.github.io/DataTable-AltEditor/example/12_inline_buttons/example12.html
