### ISSUE TITLE
Populating select options from external json file

### ISSUE THREAD

**Issue by Samuel-Momoh** [KasperOlesen/DataTable-AltEditor#125]
Hi, I was able to implement fetching select options from an external json file. The options are loaded correctly into the modal, but the edit modal is not fetching any selected data from the table into the modal for editing. And also is they a way to hide the select part of the modal on edit

**Comment by luca-vercelli** [comment]
Sorry, the question is not very clear. What it means _the edit modal is not fetching any selected data_ ? 
Did you already see [example 6](https://luca-vercelli.github.io/DataTable-AltEditor/example/06_select_datepicker/example6.html)?

**Comment by Samuel-Momoh** [comment]
What i mean is that the modal pops up with empty fields when edit button is clicked, this error occurs when i tried populating the select field from external source

**Comment by luca-vercelli** [comment]
I think you should have some error in console.

**Comment by Samuel-Momoh** [comment]
Thanks i was able to resolve it, and to my second question i tried implementing the workaround in #108  only the value got hidden leaving label. is possible to Hide the entire field set i.e including the value and label 
![image](https://user-images.githubusercontent.com/57851580/85639357-6bddf980-b680-11ea-9a99-1eb7c2b3800e.png)

**Comment by luca-vercelli** [comment]
You should play with jQuery "Tree traversal" methods. As in #108 ,

    $(modal_selector).find("#customer").closest("div").hide();

should do the trick (notice the use of "closest" function). If that doesn't work, maybe `closest("div").parent().closest("div")` could work.

**Comment by sadeghbarati** [comment]
same issue

I have different options by rows and options can't be static 

``` javascript
options: function () {
   $.ajax();
},
```

**Comment by luca-vercelli** [comment]
@sadeghbarati maybe you can play wih the `editorOnChange` property?

**Comment by sadeghbarati** [comment]
can you provide an example

@luca-vercelli

**Comment by luca-vercelli** [comment]
you can look at https://luca-vercelli.github.io/DataTable-AltEditor/example/07_dependent_select/example7.html it seems very close to your case

**Comment by sadeghbarati** [comment]
thanks for suggestion
in my console throw this error

`$.escapeSelector is not a function`


Uncaught TypeError: $.escapeSelector is not a function
    at altEditor.createDialog (dataTables.altEditor.free.js:694)
    at altEditor._openEditModal (dataTables.altEditor.free.js:288)
    at _Api.<anonymous> (dataTables.altEditor.free.js:188)
    at action (dataTables.buttons.js:574)
    at HTMLAnchorElement.<anonymous> (dataTables.buttons.js:589)
    at HTMLAnchorElement.dispatch (jquery-1.12.4.js:5226)
    at HTMLAnchorElement.elemData.handle (jquery-1.12.4.js:4878)

**Comment by luca-vercelli** [comment]
You are right, there was a bug, I have just commited a patch, can you try again? (I also filed issue #140).

**Comment by sadeghbarati** [comment]
I got no error in the console if I have a question again i'll come back here

thanks

**Comment by sadeghbarati** [comment]
this is my code 

``` javascript
editorOnChange: function (event, altEditor) {
   var data = ( hidden data in table per row );

   var thisUrl = '@Url.Action("BindComboListOfPattern", "Service")' + '?ListCode=' + data;
   $.ajax({
      type: "GET",
      url: thisUrl,
      dataType: "json",
      complete: function (xhr, status) {
         var data = xhr.responseText;
         if (xhr.status == 403 || xhr.status == 401) {
             //GoToLogOffPage();
          }
      },
      success: function (options) {
        console.log(options);
        //var PatternTitle = $(altEditor.modal_selector).find('#PatternTitle');
        //altEditor.reloadOptions(PatternTitle, options);
      }
   });

},
```


excepted behavior: `get ajax for once`

actual behavior: `ajax call like setInterval - ajax call every 300 miliseconde`


--------------------------------------

my options API is something like this not just a simple array, how to use js literals syntax for templating


``` json
[
   {
      "Disabled": false,
      "Group": null,
      "Selected": false,
      "Text": "option one",
      "Value": "7Fl5IDjhmn3e4IDNevW7PKDmn3e4eAo2ooto2oot"
   },
   {
      "Disabled": false,
      "Group": null,
      "Selected": true,
      "Text": "option two",
       "Value": "u8C6ifPcj5Aum07SlyrkpQo2ooto2oot"
   }
]
```

**Comment by sadeghbarati** [comment]
@luca-vercelli can you help I have no Idea

**Comment by luca-vercelli** [comment]
@sadeghbarati yes, you must change the object that you pass to `reloadOptions`. E.g.

    success: function (data) {
        var options = {};
        data.each( function (x) {
            options[x.Text] = x.Value;
        });
        var PatternTitle = $(altEditor.modal_selector).find('#PatternTitle');
        altEditor.reloadOptions(PatternTitle, options);
    }

Then you have to deal with the `Selected` attribute too.

**Comment by sadeghbarati** [comment]
ok thanks for answer

how to make it unchangeable?


for example, select element is created and then
I click an option except for the first one and its reFetch options again

**Comment by luca-vercelli** [comment]
Sorry I do not understand your request
Do you mean to make disabled some option values? https://stackoverflow.com/questions/2867362

**Comment by sadeghbarati** [comment]
![screen-capture](https://user-images.githubusercontent.com/17789047/93069347-cd67a000-f692-11ea-803e-cdf0fe0e0015.gif)

**Comment by luca-vercelli** [comment]
lol

**Comment by sadeghbarati** [comment]
xD
stranger things
datatables editation

**Comment by luca-vercelli** [comment]
@sadeghbarati did you solve your "reload" issue? I don't see your comments anymore on this thread.
Maybe you are reloading the same SELECT menu that you are just modifying?
If you did not solve, please open a separate issue for that.

**Comment by sadeghbarati** [comment]
it solved with ctrl f5 😐

**Comment by sadeghbarati** [comment]
@luca-vercelli 

https://github.com/KasperOlesen/DataTable-AltEditor/blob/4f307b1b9c9cfe82d75cd8a309d4fa523164949c/src/dataTables.altEditor.free.js#L989

`$select.trigger('change');` loops ajax data


the issue I faced after solving previous problems: 

1. empty editorOnChange ajax data empty `obj` empty `arr`

2. difference text between countryOptions and another country text like `Poland` in editorOnChange ajax call
