### ISSUE TITLE
Help ( Question) Add, edit, delete in memory object

### ISSUE THREAD

**Issue by ducanh1296** [KasperOlesen/DataTable-AltEditor#129]
Hi im new to use datatable and i see the example **In memory objects**. I want to add row, edit, delete in client side ( it mean to add, edit the " var dataSet= [] " in the example, and after that i will be put all data with correctly to server side to update db) 
Can i do that?  Can u support me or suggest me do something. Thank alot :D

**Comment by ducanh1296** [comment]
Hi i try to show data to console and i have 
![image](https://user-images.githubusercontent.com/47854549/87849126-499e6b00-c910-11ea-9f7c-8b2c040e7e62.png)

It have 
addRowBtn: ""
undefined: "" 
didnt same to older data. And "id" not auto increase. Can i fix this ?

**Comment by luca-vercelli** [comment]
Hello.
There is no way to "auto increase" a row value, AFAIK. Usually this is done server-side.

And, you are right, there is a bug somewhere, so that "addRowBtn" is considered part of the object. "addRowBtn" is the id of the "Add" button.

**Comment by isgleb** [comment]
> Hi im new to use datatable and i see the example **In memory objects**. I want to add row, edit, delete in client side ( it mean to add, edit the " var dataSet= [] " in the example, and after that i will be put all data with correctly to server side to update db)
> Can i do that? Can u support me or suggest me do something. Thank alot [:D]

found solution for this issue. Code below is taken from the example2.js
the only difference is that I added "onAddRow",  dealing with onEditRow and onDeleteRow will be probably the same.




`   var myTable;

  myTable = $('#example').DataTable({
    "sPaginationType": "full_numbers",
    data: dataSet,
    columns: columnDefs,
	dom: 'Bfrtip',        // Needs button container
    select: 'single',
    responsive: true,
    altEditor: true,     // Enable altEditor
    buttons: [{
            text: 'Add',
            name: 'add'        // do not change name
          },

          {
            extend: 'selected', // Bind to Selected row
            text: 'Edit',
            name: 'edit'        // do not change name
          },

          {
            extend: 'selected', // Bind to Selected row
            text: 'Delete',
            name: 'delete'      // do not change name
         }],

// here I add onAddRow
          onAddRow: function(datatable, rowdata, success, error) {
          
                  newRow = {id: "", name: rowdata["name"], position: rowdata["position"], .... all the other columns}
                  dataSet.push(theRow);
                  success(rowdata);

  });

[`]

**Comment by luca-vercelli** [comment]
Instead of declaring a `newRow`, maybe you can unset unwanted property from `rowdata`?

    rowdata.addRowBtn = undefined
    rowdata.undefined = undefined

If this works, we could modify the `rowdata` inside `_addRowData()` before calling `onAddRow`.

**Comment by ducanh1296** [comment]
its a long time ago but thanks a lot guys
