### ISSUE TITLE
Callback for "Delete" button generating bad json and generating bad URL

### ISSUE THREAD

**Issue by paulomac1000** [KasperOlesen/DataTable-AltEditor#13]
Steps to reproduce:
1. Select row
2. Press delete button
3. Debug for loop in line 475. JSON has the wrong key, for example:
{0: "08:00:00"}
instead of
{Hour: "08:00:00"}
4. generated URL is also wrong .../action?0=08%3A00%3A00

Solution:
Edit line 477 from
jsonDataArray[dt.context[0].aoColumns[i].idx] = adata.data()[0][dt.context[0].aoColumns[i].data];
to
jsonDataArray[dt.context[0].aoColumns[i].data] = adata.data()[0][dt.context[0].aoColumns[i].data];

**Comment by luca-vercelli** [comment]
Your solution is not full, it works only if .data attribute exists
