### ISSUE TITLE
Help ( Question) remove column from table, with ability to edit it

### ISSUE THREAD

**Issue by pyweb-wa** [KasperOlesen/DataTable-AltEditor#132]
how I can remove column from table but still can edit the removed column in edit or  in add ?
for example if my table for users login info, I need to remove password field from table view but in edit and add button I need to edit password or add new password

**Comment by luca-vercelli** [comment]
Hi, this is a common question. Unluciky this is not supported so far.
You can find some workarounds browsing issues #108, #120, #126, ...
