### ISSUE TITLE
General questions about Example #2

### ISSUE THREAD

**Issue by schonhose** [KasperOlesen/DataTable-AltEditor#133]
Example #2 deals with the use of object-based datatable rows in memory. I have a couple of questions about this example that I was unable to answer myself:

- Does adding, editing and deleting rows from the `dataSet` variable also update this variable?
- When adding and editing the console.log shows the new object. Can this be disabled?
- Similar to the situation above, the console.log writes a message, e.g., Missing AJAX configuration for INSERT. Does this mean we have to provide a function for INSERT, DELETE and UPDATE to update the `dataSet` variable?

Some background information on how I would like to use the editor. I got a dataset in a variable that I use to plot using a JS plotting library. I want to use this dataset into datatables in combination with the alt-editor. Since the dataset is in memory, I need the editor to update the contents of the variable dataset on all actions.

I figure that I can use the AJAX configuration also for the redrawing of the chart after an INSERT, DELETE or UPDATE action. But before that I need to know if the variable is updated by the plugin or I have to write code to do this myself.

**Comment by luca-vercelli** [comment]
Hello @schonhose . I'll try to answer everything.

>     * Does adding, editing and deleting rows from the `dataSet` variable also update this variable?

Not sure of this, I think not. That variable is used only for initialization, it is not linked to the Datatable, AFAIK. Don't rely on this.

> When adding and editing the console.log shows the new object. Can this be disabled?

No it can't. It's some debug code that I forgot somewhere in the code. You can safely find and remove every "console.log" line in the script.

> Similar to the situation above, the console.log writes a message, e.g., Missing AJAX configuration for INSERT. Does this mean we have to provide a function for INSERT, DELETE and UPDATE to update the dataSet variable?

Not exactly. You have to provide these functions (callbacks) if you want to update you backed - whatever it is. Usually you want call some a server, via AJAX (example n. 3). In your case, you can use these callbacks to update `dataSet` variable..

**Comment by schonhose** [comment]
Thanks @luca-vercelli!

One more question: do you have any suggestion on how to find the object in the `dataSet` variable that needs to be updated?

**Comment by luca-vercelli** [comment]
Uhm, I never had to do that...
Maybe do you have some (readonly) `id `column in your `dataSet`, and you can search for it?

**Comment by luca-vercelli** [comment]
@schonhose  please let us know if you solved that, and if this issue can be closed.

**Comment by schonhose** [comment]
This can be closed as far as I am concerned.
