### ISSUE TITLE
Multiple datatables existing on page

### ISSUE THREAD

**Issue by wolfgangjt** [KasperOlesen/DataTable-AltEditor#134]
A bug where if you have multiple datatables loaded on the page, the line for languages breaks on the _setup function.

`this.language = DataTable.settings.values().next().value.oLanguage.altEditor || {};`

says that values() is undefined. Settings stores the info of datatables [0], [1], [2] ...

I got around it by changing the line to the following:

```
var numberOfDTs = DataTable.settings.length;
this.language = DataTable.settings[numberOfDTs-1].oLanguage.altEditor || {};
```

because in all cases on my page the most recent datatable will be the highest number in the list.

**Comment by luca-vercelli** [comment]
@wolfgangjt I just tried, and I do not experience this issue.
What version of Datatable are you using? can you provide any fiddle?

**Comment by wolfgangjt** [comment]
Sorry i forgot about this issue while working on other parts. I cannot provide anything easily, my code is on an intranet network. We are using the version of datatables 1.10.12

Could be a variety of different issues I guess? I have the main datatable on the main page, and the secondary datatable is being loaded in a modal. Seems to be just a me-issue but I worked around it. Doesn't look like anyone else has had the issue but thanks!
