### ISSUE TITLE
After Successful edit or add, the modal does not close.

### ISSUE THREAD

**Issue by rafaelsanchezrd** [KasperOlesen/DataTable-AltEditor#135]
Is there a way that after successful Edit of record or Adds new record the modal close after clicking the Save button?

**Comment by luca-vercelli** [comment]
It is supposed to do that.
Did you browse the examples?


Il sab 8 ago 2020, 14:00 rafaelsanchezrd <notifications@github.com> ha
scritto:

**Comment by rafaelsanchezrd** [comment]
Hello :), I'm really enjoying this plug-in and leaning a lot from it,
Related to Close Window  I don't see this happen even in the example, in the example you have in the modal Window you need to click a  Close button
https://luca-vercelli.github.io/DataTable-AltEditor/example/03_ajax_objects/example3.html
![image](https://user-images.githubusercontent.com/5248544/89719554-8b628480-d997-11ea-9c0a-a9d14d46b839.png)

would be good that after you add or edit a record the windows close and then you can control the event

**Comment by wolfgangjt** [comment]
You could probably edit the script yourself and trigger the modal to close on the callback.

**Comment by rafaelsanchezrd** [comment]
do you have some pseudocode or example I can follow?

if its supposed to close after successful edit or add why it shows a close button?

**Comment by luca-vercelli** [comment]
> if its supposed to close after successful edit or add why it shows a close button?

Sorry, I was wrong. It is **not** supposed to do that. After the save, a message "Success" is presented to the use, and he must close the window by himself. (this is an old-fashioned behaviour). 

If you fix this issue, please send a PR.

**Comment by wolfgangjt** [comment]
For anyone interested, what I did was go into the code and make code changes in the _addRowCallback, _deleteRowCallback, and _editRowCallback functions:

Remove the lines 
* var message = '<div class="alert....;
* $(selector + ' .modal-body').append(message);

at the end of the function add:
* $(selector).modal('hide');

**Comment by luca-vercelli** [comment]
Thank you @wolfgangjt.

**Comment by luca-vercelli** [comment]
Added new datatable option that tells if the dialog box should be closed or not after successful edit
