### ISSUE TITLE
Unsupported nested objects

### ISSUE THREAD

**Issue by mesiarm** [KasperOlesen/DataTable-AltEditor#15]
Steps to reproduce:

Use column with name type.name (nested object)
You got undefined
Solution:
Edit all  "for (var j in columnDefs) {" loops
add to begining of loop body:
var inputValue = adata.data()[0][columnDefs[j].name];
if (columnDefs[j].name.indexOf(".") !== -1) { //inner object through dot notation
	var splitted = columnDefs[j].name.split(".");
	inputValue = adata.data()[0][splitted[0]][splitted[1]];
}
then replace all "adata.data()[0][columnDefs[j].name];" with inputValue

**Comment by luca-vercelli** [comment]
I have improved something today, about this subject
