### ISSUE TITLE
How to handle a CheckBox?

### ISSUE THREAD

**Issue by rafaelsanchezrd** [KasperOlesen/DataTable-AltEditor#150]
Hello I need to put a field that is a checkbox bot is showing as and Input, is there a wat yo specify a type that will make it show as a checkbox?

**Comment by andrefd17** [comment]
You can add into the **columnDefs** for the column that you want to be a checkbox something like this:

`{
                    data: "include",
                    title: "Include",
                    type: "checkbox",
                    render: function (data, type, row, meta) {
                        return '<input type="checkbox" checked="checked" onclick="return false">'
                    }
                },`

inside the render function you can also handle the checkbox state as well by managing the "checked" attribute

**Comment by luca-vercelli** [comment]
Thank you @andrefd17 for sharing this
