### ISSUE TITLE
Json response format to return error message

### ISSUE THREAD

**Issue by igorpooh1978** [KasperOlesen/DataTable-AltEditor#152]
Could you please provide a example of format json response message when i make error message on server side
e.g.
```
{
'error':'Oops, something wrong'
}
```
or
```
{

'error':[
{'message':'error message #1'},
{'message':'error message #1'},
]
}
```
or something other ?
Which is correct response?

**Comment by luca-vercelli** [comment]
Hello, you should look at the _errorCallback function. It seems that it
expects something like

{
'errors':[
['error message #1'],
['error message #2']
]
}

However I cannot try it now.


Il sab 26 set 2020, 10:58 IgorPukhlikov <notifications@github.com> ha
scritto:

**Comment by igorpooh1978** [comment]
Just checked it's correct.
Thanks a lot !
