### ISSUE TITLE
Dependent Select Example Delete button

### ISSUE THREAD

**Issue by sadeghbarati** [KasperOlesen/DataTable-AltEditor#158]
https://luca-vercelli.github.io/DataTable-AltEditor/example/07_dependent_select/example7.html

country and town value is `undefined` not just in example in my project return `undefined`
coz it's can't access the options that create on ajax call

https://github.com/KasperOlesen/DataTable-AltEditor/blob/d4d38df4a1da05ebb06eb0e5ae662925c9220113/src/dataTables.altEditor.free.js#L436-L453

**Comment by luca-vercelli** [comment]
Fixed
