### ISSUE TITLE
Add support for checkbox type and datetime type

### ISSUE THREAD

**Issue by mesiarm** [KasperOlesen/DataTable-AltEditor#16]
It would be great to add support for checkbox type (showing checkbox in add and edit modal) and datetime type (showing bootstrap datepicker)

**Comment by luca-vercelli** [comment]
I have just added some support on datepickers

**Comment by mjbernot** [comment]
@mesiarm @luca-vercelli checkbox types have been added, please let me know if something isnt working as expected.
