### ISSUE TITLE
sending requests

### ISSUE THREAD

**Issue by isgleb** [KasperOlesen/DataTable-AltEditor#162]
Great plugin. Thanks to author.
The issue is a solution in case if someone would have same problems with the requests.

As a beginner and as it was my first experience of JavaScript and jQuery, I had problems with sending correct requests to server (these problems could be connected to jQuery version or anything. The fact is that requests written in example3 style didn't work. Server side was on Java Spring and worked perfect, tested by Postman). Debugging of the requests was even harder due to cashing. Here below correctly working requests:

....

        onAddRow: function(datatable, rowdata, success, error) {
            $.ajax({
                url: '/example',
                type: 'POST',
                contentType: "application/json",
                data: JSON.stringify(rowdata),
                success: success,
                error: error
            });
        },

        onDeleteRow: function(datatable, rowdata, success, error) {
            $.ajax({
                url: '/example?' + $.param({id: rowdata.id}),
                type: 'DELETE',
                success: success,
                error: error
            });
        },

        onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                url: '/example?' + $.param({id: rowdata.id}),
                type: 'PUT',
                success: success,
                error: error
            });
        }
....

**Comment by sadeghbarati** [comment]
share full code and hide whatever you worry about

using `editorOnChange` crash or these three functions `onAddRow, onDeleteRow, onEditRow` ?

**Comment by isgleb** [comment]
> share full code and hide whatever you worry about
> 
> using `editorOnChange` crash or these three functions `onAddRow, onDeleteRow, onEditRow` ?

the rest part of the file was copied from example3 without changes.
also in the project is used template https://www.wrappixel.com/demos/free-admin-templates/matrix-admin/index.html
this template includes and downloads jQuery v3.3.1 (old stuff). I don't really know if it could affect the work of altEditor

used only these three functions

**Comment by luca-vercelli** [comment]
Thank you @isgleb
