### ISSUE TITLE
Understanding AltEditor - receiving changed values

### ISSUE THREAD

**Issue by telemach1337** [KasperOlesen/DataTable-AltEditor#168]
I am newbie but would like to understand basic logic in using AltEditor.

I would like to test very simple scenario where I have single JSON file like mock_svc_load.json which I load with DataTables (no problem with that) and then edit single row, click Edit and have have this changes saved in the same mock_svc_load.json.

Example[ #3](https://luca-vercelli.github.io/DataTable-AltEditor/example/03_ajax_objects/example3.html) I can open from HDD but not using WAMP or webhosting (editor doesn't come up).

I see section 

```
onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                // a tipycal url would be /{id} with type='POST'
                url: url_ws_mock_ok,
                type: 'GET',
```

so my understanding is that GET should be replaced with POST which is sending my changes via POST to url_ws_mock_ok that is a script which is reading POST and making changes accordingly but in real I see that it works differently; 

AltEditor is sending changes with POST to some script (but how and where do I configure location of this script ???), then this script is making changes to  mock_svc_load.json and placing a copy of changed row to url_ws_mock_ok which is used by AltEditor to read by GET.

I can write simple script to receive POST and do replace and copy to url_ws_mock_ok but how do I communicate AltEditor with this script ???

**Comment by luca-vercelli** [comment]
I try to answer.
You need a webservice to do real ajax!
When you write "_I can write simple script to receive POST_" I imagine you are writing a webservice on some PHP server. So you can change the above lines into something like

```
onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                url: "/path/to/edit/webservice/" + rowdata.id,
                type: 'POST',
                data: rowdata,
                success: success,
                error: error
            });
        }
```

The webservice must return the line that you just saved, possibly modified by server.
