### ISSUE TITLE
AltEditor with Database connection

### ISSUE THREAD

**Issue by sarbast1985** [KasperOlesen/DataTable-AltEditor#169]
Hi,
I would like to use AltEditor with database so my question how to do it?

Thanks

**Comment by luca-vercelli** [comment]
Sorry for the delay in answer. Briefly:

- You need a database
- You need a webservice that connects to that database. PHP, Java, nodejs, or whatever. You must implement standard CRUD functionalities. You should be able googling for that, for example see https://duckduckgo.com/?q=php+crud+webservices
- Create a datatable as in [Example 3](https://luca-vercelli.github.io/DataTable-AltEditor/example/03_ajax_objects/example3.html)
- Configure methods `onAddRow, onEditRow, onDeleteRow` so they call your webservices.

**Comment by sarbast1985** [comment]
thanks alot
