### ISSUE TITLE
Unknown parameter when editing

### ISSUE THREAD

**Issue by markrjones** [KasperOlesen/DataTable-AltEditor#171]
Hi,

I was having trouble with a Datatables error message: "Requested unknown parameter "email" for row 2, column 0.

That's an example, depending on the columns in the table and position the parameter could change.

If found a resolution in this Stackoverflow question: https://stackoverflow.com/questions/56857141/using-datatables-alteditor-requested-unkown-parameter

The fix was as follows:
-------------------------------------------
I changed the line 285 of dataTables.altEditor.free.js

that._editRowCallback(data,b,c,d,e); changed to that._editRowCallback(rowDataArray,b,c,d,e);

Complete section:

that.onEditRow(that,
                    rowDataArray,
                    function(data,b,c,d,e){ that._editRowCallback(rowDataArray,b,c,d,e); },
                    function(data){ that._errorCallback(data);
                });
------------------------------------------

This worked for me but I really have no idea why. I wanted to check with you to see if this is a fix that makes sense to you. I should say, I only have this problem when I am using ajax and not when using an array to populate the table.

**Comment by luca-vercelli** [comment]
As I just wrote on StackOverflow:

_IMHO this is not a good solution. `rowDataArray` is the data that the browser sent to the server, while `data` is the data that the server returned to the client. This means that you are ignoring every server-side modification to your data. Probably you have to better analyze what server returns. If you really what to ignore server-side stuff, you should modify the function `onEditRow` passed to the constructor._

**Comment by markrjones** [comment]
Thanks for the quick response, it's appreciated.

Well I am certainly not keen on altering the code of the product hence why I chose to post here for your comments. Also, your explanation of the difference between the two has helped me understand where my issue is, so it should help me fix my problem, which for sure is about the data that my ajax is returning from the server side.
