### ISSUE TITLE
How to set default value for Select type when adding new row?

### ISSUE THREAD

**Issue by thang206** [KasperOlesen/DataTable-AltEditor#173]
Hi, I'd like to set default value for a Select when adding new row. I've tried "defaultValue" but it doesn't work. Please kindly advise. Thanks

**Comment by sadeghbarati** [comment]
Hi

1. Do you want the `select` to have a value in the `addRow modal`?
1.1 using `select2` or `normal select` element ?
1.2 maybe `editorOnChange` or `addModalOpen` can help you; second one is not in the github source it's my custom code added to altEditor - [altEditor-extended.zip](https://github.com/KasperOlesen/DataTable-AltEditor/files/6140293/altEditor-extended.zip)






---
2. Or you want **`after`** add new row that column have a data ?

**Comment by thang206** [comment]
Hi sadeghbarati, I'm sorry for not describing the issue clearly. Yes, I'd like normal select to have value in <code>addRow modal</code>. The options are loaded from Ajax call. Ex, the result Select contains options which are "1", "2", "3" and I need the default value is always "2" whenever <code>addRow modal</code> shows.

**Comment by sadeghbarati** [comment]
can you explain the return of **ajax** call or show some **code** ?

1. with `altEditor-extended` selector is altEditor's `modal_selector`
``` javascript 
addModalOpen: function (altEditor, dt, selector) {
    $(selector).find(#selectElement).val(value of option test both String '2' or Number 2);
},
```


2 : `altEditor.reloadOptions(#selectElement, options);` and select option two just like 1

**Comment by thang206** [comment]
Thank you so much sadeghbarati.  The <code>altEditor-extended</code> does help to resolve the problem.

**Comment by delegate-it** [comment]
Dear sadeghbarati

I interested to know more about the altEditor-extended and more specifically, I would like to set a boolean variable to true when addModalOpen triggers. Can you please send me a working example ?
