### ISSUE TITLE
Spanish translation not working

### ISSUE THREAD

**Issue by Sebas1245** [KasperOlesen/DataTable-AltEditor#175]
I tried to use the option to translate the table to spanish, but I am not sure if it is not working or if I am just not using it correctly. 

I placed the following in the language option:
```javascript
language: {
        url: 'dataTables.spanish.json'
},
```
```javascript
language: {
        url: '//cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish_Mexico.json'
},
```
Neither of these worked, and plugging in the JSON in [this page](https://datatables.net/plug-ins/i18n/Spanish_Mexico.html) worked only partially.

**Comment by luca-vercelli** [comment]
Excuse me, is this a problem with AltEditor or with DataTable's ?

In the latter case you should better ask on their forum: 
https://datatables.net/forums/


Il 26/03/2021 00:44, Sebastián Andrés Saldaña Cárdenas ha scritto:

**Comment by Sebas1245** [comment]
I can see now that it is an issue with DataTables, thank you for referring me to the right place!
