### ISSUE TITLE
[Bug Report] editorOnChange && Unique check

### ISSUE THREAD

**Issue by thang206** [KasperOlesen/DataTable-AltEditor#176]
Hi @luca-vercelli ,

While working with altEditor, I found 2 bugs that may cause others failed if they fall into the same scenario like myself

1. editorOnChange: missing escapeSelector when callback `change` event. If the data is nested object (ex `parents.child`), the `change` wont be fired.

Original code:

```
                    // custom onchange triggers
                    if (columnDefs[j].editorOnChange) {
                        // $.escapeSelector requires jQuery 3.x
                        $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).attr('alt-editor-id', this._quoteattr(j));
                        $(selector).find("#" + columnDefs[j].name).on('change', function(elm) {
                            var f = columnDefs[$(this).attr('alt-editor-id')].editorOnChange;
                            f(elm, that);
                        });
                    }
```

Modified code:

```            
                    // custom onchange triggers
                    if (columnDefs[j].editorOnChange) {
                        // $.escapeSelector requires jQuery 3.x
                        $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).attr('alt-editor-id', this._quoteattr(j));
                        $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).on('change', function(elm) {
                            var f = columnDefs[$(this).attr('alt-editor-id')].editorOnChange;
                            f(elm, that);
                        });
                    }
```

**Comment by luca-vercelli** [comment]
I agree for the first issue, I have just pushed the modification that you suggest.
I am not sure yet about the second one.

**Comment by thang206** [comment]
for the second issue, please take a look at pseudo data below

ID (Unique)            Name 
----------------------------------------
S01                         Tom
S02                         Mary
S03                         David

- If I'm selecting at row S02 then adding a new record.
- Input "S02" for ID field and "Lisa" for Name field then save. 
-> It wont raise unique error message but successfully insert data.

ID (Unique)            Name 
----------------------------------------
S01                         Tom
S02                         Mary
S03                         David
S02                         Lisa

Look at the code for this case.  `selectedCellDat = S02`, `ColData = [S01, S02, S03]` 
The code to check and raise duplicate error is `if (target.val() == colData[j] && colData[j] != selectedCellData)`
As you can see the  `selectedCellDat` is always equal to `colData[j]`. Therefore, there's no error raised.
