### ISSUE TITLE
Proposal: Breaking Change for OnEditRow

### ISSUE THREAD

**Issue by twoxfh** [KasperOlesen/DataTable-AltEditor#178]
I appreciate the extended Datatables functionality and all the effort. I am proposing sending the original row data from _editRowData to OnEditRow. This would allow the developer to find the changed keys and only send updates. Additionally, 
 improve network performance for large tables with lots of columns.  

Small changes: 
Line 346:  var orginalRowDataArray = adata.data()[0];
Add to end of Line 387 : originalRowDataArray,

Thoughts?

**Comment by luca-vercelli** [comment]
Hello. Thank you. Why do you say this is a "breaking" change? I think the old applications would work without problems. They just do not use this last parameter. Am I wrong?

**Comment by twoxfh** [comment]
Ah yes, add it after error instead of rowdata? Depends on how picky your about order :)

**Comment by luca-vercelli** [comment]
Yes, I mean after error callback function:

```
                     that.onEditRow(that,
                            rowDataArray,
                            function(data,b,c,d,e){ that._editRowCallback(data,b,c,d,e); },
                            function(data){ that._errorCallback(data);},
                            orginalRowDataArray);

```
This would not break compatibility.

**Comment by twoxfh** [comment]
Sounds good to me.
