### ISSUE TITLE
Set default value for add modal is not displaying when adding a new record

### ISSUE THREAD

**Issue by delegate-it** [KasperOlesen/DataTable-AltEditor#182]
I am trying to have a default value for one of the columns when adding a new record.
I have put column definition as below
`{
 data: "qty_rcv",
 type: "text",
 value: "0.00",
 title: "Received Qty",
 class: "text-right"
},`
<img width="489" alt="Screenshot 2021-04-16 at 09 43 42" src="https://user-images.githubusercontent.com/45656979/114989991-5bf60700-9e98-11eb-8fe0-11bc914b2bf9.png">

Below is the HTML
`<table
                    style="width: 100%"
                    id="itemsTable"
                    class="table table-bordered table-striped"
                  >
                    <thead>
                      <tr>
                        <th>Id</th>
                        <th>Item</th>
                        <th>Ordered Qty</th>
                        <th>Received Qty</th>
                        <th>Unit of Measure</th>
                        <th>Price per Unit</th>
                        <th>Total Price</th>
                        <th>Tax</th>
                        <th>Delivery</th>
                      </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                      <tr>
                        <th colspan="6" class="text-right">Total Order (inc. Tax):</th>
                        <th colspan="2" style="text-align: right"></th>
                        <th></th>
                      </tr>
                    </tfoot>
                  </table>`
Below is the javascript
`var columns = [
          {
            data: "id",
            title: "Id",
            type: "readonly",
            visible: false,
            searchable: false,
          },
          {
            data: "item",
            title: "Item",
            type : "select",
            options : item_options,
            select2 : { width: "100%"},
            render: function (data, type, row, meta) {
              if (data == null || !(data in item_options)) return null;
              return item_options[data];
            },
            editorOnChange : function(event, altEditor) {
              var item_id = $(event.currentTarget).val();
              $.ajax({
                  url: '/mrp/api/items/item/' + item_id + '/',
                  type: 'GET',
                  success: function(data) {
                      var unit = $(altEditor.modal_selector).find('#unit');
                      var cost_per_unit = $(altEditor.modal_selector).find('#cost_per_unit');
                      cost_per_unit.val(data.price);
                      // unit.val(data.unit_usage);
                      if (data.unit_usage) {
                        var unitOption = new Option(data.unit_usage_name, data.unit_usage, true, true);
                        unit.append(unitOption).trigger('change');
                      }
                  }
              });
            }
          },
          {
            data: "quantity",
            editorOnChange : function(event, altEditor) {
              var quantity = $(event.currentTarget).val();
              var cost_per_unit = $(altEditor.modal_selector).find('#cost_per_unit').val();
              var total_ex_tax = $(altEditor.modal_selector).find('#total_ex_tax');
              var tax = $(altEditor.modal_selector).find('#tax');
              quantity = quantity == "" ? 0 : quantity;
              cost_per_unit = cost_per_unit == "" ? 0 : cost_per_unit;
              var total = quantity * cost_per_unit;
              total_ex_tax.val(total);
              var taxValue = total * taxRate / 100;
              tax.val(taxValue);
            }
          },
          {
            data: "qty_rcv",
            type: "text",
            value: "0.00",
            title: "Received Qty",
            class: "text-right"
          },
          {
            data: "unit",
            title: "Unit",
            type : "select",
            options : unit_options,
            select2 : { width: "100%"},
            render: function (data, type, row, meta) {
              if (data == null || !(data in unit_options)) return null;
              return unit_options[data];
            }
          },
          {
            data: "cost_per_unit",
            title: "Price per unit",
            className: "text-right",
            render: $.fn.dataTable.render.number(',', '.', 2, 'R '),
            editorOnChange : function(event, altEditor) {
              var quantity = $(event.currentTarget).val();
              var cost_per_unit = $(altEditor.modal_selector).find('#cost_per_unit').val();
              var total_ex_tax = $(altEditor.modal_selector).find('#total_ex_tax');
              var tax = $(altEditor.modal_selector).find('#tax');
              quantity = quantity == "" ? 0 : quantity;
              cost_per_unit = cost_per_unit == "" ? 0 : cost_per_unit;
              var total = quantity * cost_per_unit;
              total_ex_tax.val(total);
              var taxValue = total * taxRate / 100;
              tax.val(taxValue);
            }
          },
          {
            data: "total_ex_tax",
            title: "Total exc. Tax",
            className: "text-right",
            type: "readonly",
            render: $.fn.dataTable.render.number(',', '.', 2, 'R ')
          },
          {
            data: "tax",
            title: "Tax",
            className: "text-right",
            type: "readonly",
            render: $.fn.dataTable.render.number(',', '.', 2, 'R ')
          },
          { 
            data: "delivery_status", 
            type: "hidden",
            className: "text-right align-middle" 
          },
        ];`

**Comment by luca-vercelli** [comment]
The problem arise for 0.00 only? other values are displayed correctly?
I think the bug is here:

https://github.com/KasperOlesen/DataTable-AltEditor/blob/ae27297c3eed2aadba785130655126c0d190b196/src/dataTables.altEditor.free.js#L595

0.00 is considered as empty and treated as ''

This feature has been added recently by @thetechnician94 , he may be interested in this.

**Comment by thetechnician94** [comment]
With a quick test in my system I couldn't reproduce. I'll try again later with a clean system to be sure.

**Comment by thetechnician94** [comment]
Sorry for getting back so late, but I did confirm that I cannot reproduce the issue in a clean repo.

**Comment by delegate-it** [comment]
Thanks thetechnician94 and apologies for the late response. 
I changed the AltEditor.js library to yours and think are working as expected.

Thank you again.
