### ISSUE TITLE
select options in an object not sorting alphabetically

### ISSUE THREAD

**Issue by delegate-it** [KasperOlesen/DataTable-AltEditor#183]
I would like to sort the options for a select2 alphabatecally. 
For example, employeeOptions = { "1" : "Employee", "2" : "Official" , "3" : "Director" }; I want to sort the data alphabetically when displayed to the user. 

How can I do that?

**Comment by delegate-it** [comment]
The data is sorted in alphabetically in the employeeOptions by the text. The id is the primary key that is coming from the DB. The thing is that the select 2 is always sorting them by the id.

**Comment by sadeghbarati** [comment]
These sources might help

https://github.com/sindresorhus/sort-on
https://github.com/sindresorhus/sort-keys

**Comment by delegate-it** [comment]
https://github.com/sindresorhus/sort-on
https://github.com/sindresorhus/sort-keys
The above references won't help because my employeeOptions is already sorted by text. I don't need to sort it. Select2 is sorting it by the id when inserting the select options.

**Comment by delegate-it** [comment]
I worked around the problem by creating 2 arrays. One to hold the IDs and one to hold the text.
  var itemOptions = [];
  var itemOptionsIds = [];

The data come from an API Call sorted by text. 

then I loop through the options and add them one by one in the same order from the database.
for (var i = 0; i < data.length; ++i) {
   itemOptions.push( data[i]['name']);
   itemOptionsIds.push( data[i]['id']);
}
Then on Adding an item I perform the below to save the id 
onAddRow: function (datatable, rowdata, success, error) {
            //add item to the rowdata 
            var item = rowdata["item"];
            var index = itemOptions.findIndex(function(value) { return item == value; });
            var item_id = 0;
            if (index != -1) {
              item_id = itemOptionsIds[index];
            } 
            rowdata["item"] = item_id;

**Comment by delegate-it** [comment]
I just read in the docs that  there is a property that you can use to sort the Select2 by label.

            optionsSortByLabel: true,

**Comment by thetechnician94** [comment]
@delegate-it They will get you like that :). Glad you found a solution
