### ISSUE TITLE
Custom Modal, trigger after modal show ?

### ISSUE THREAD

**Issue by mmmcorpsvit** [KasperOlesen/DataTable-AltEditor#187]
can show any example please
can't understand how use alteditor:add_dialog_opened

please help

**Comment by mmmcorpsvit** [comment]
solved:
```js
    $(document).on('alteditor:add_dialog_opened', function (e) {
      console.log(e);
      console.log('fghfghfgh');
      //$.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
    });
```

how i can assign for specific table?

**Comment by sadeghbarati** [comment]
#173 


take a look at it

`altEditor-extended` have

1. addModalOpen 
2. editModalOpen
3. deleteModalOpen 


**with these options you can assign `modal` for specific table**

---

usage of above options is just like `altEditor` options:
 
1. onAddRow
2. onEditRow
3. onDeleteRow

**Comment by mmmcorpsvit** [comment]
i need change already showed modal form via js, successful solved already
why form contain undefined field? this is bug?
