### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes'

### ISSUE THREAD

**Issue by mbaleani** [KasperOlesen/DataTable-AltEditor#2]
I get the following error in :

 //Adding text-inputs and errorlabels
         if(columnDefs[j].type.includes("text")){

"dataTables.altEditor.free.js:508 Uncaught TypeError: Cannot read property 'includes' of undefined(…)"

 Am I missing any library?

**Comment by KasperOlesen** [comment]
Did you remember to add the type attribute to the columns in the columnDef object?

**Comment by PaSch1** [comment]
I hat the same issue. In my case the IE11 doesn't support the command "include".  It works with indexOf in IE and FF. :) 

if(columnDefs[j].type.indexOf("text") >= 0){
