### ISSUE TITLE
I had to switch back to commit ffd3005 to avoid this error (`rowdata` was empty).

### ISSUE THREAD

**Issue by paulmcgann** [KasperOlesen/DataTable-AltEditor#200]
I had to switch back to commit ffd3005 to avoid this error (`rowdata` was empty).

_Originally posted by @camandel in https://github.com/KasperOlesen/DataTable-AltEditor/issues/195#issuecomment-986836244_

I am getting the same issue when using ajax, is this the same scenario you are experiencing this with or are there other scenarios this is happening too also?

**Comment by SinisterSpatula** [comment]
Having the same problem, onDeleteRow ajax call giving me illegal error, and when I console log the rowdata it is undefined.  Thank you I was going crazy trying to figure out what the issue was.  Going to try that commit now.
