### ISSUE TITLE
Datepicker example not working. 

### ISSUE THREAD

**Issue by abalter** [KasperOlesen/DataTable-AltEditor#210]
This example

https://luca-vercelli.github.io/DataTable-AltEditor/example/06_select_datepicker/example6.html

Throws an error when adding or editing a row, and then corrupts the data in the row.

![image](https://user-images.githubusercontent.com/5349876/166876697-d012da5e-b290-4918-87c2-ea89b55d07e5.png)

![image](https://user-images.githubusercontent.com/5349876/166876751-00cd9ed6-0b9c-4e12-b733-f27a48ba0a45.png)

Name reverts to Tiger Nixon and Degree not registered.

**Comment by luca-vercelli** [comment]
You are right, json mock response was broken. Now fixed. Pull #17 .

**Comment by abalter** [comment]
Thanks for getting right on that! However, it still is throwing an error in the modal. However, there is no error in the console, so I can't figure out what in the code might be causing that.

![image](https://user-images.githubusercontent.com/5349876/167220949-98458961-3f2a-4dee-8b76-54f2fc2865f4.png)


(Sorry, I thought I had posted this already a couple of days ago)

**Comment by luca-vercelli** [comment]
The problem has been fixed today, however there can be issues with browser cache.
The file mock_svc_ok.json was not a correctly formed JSON.
