### ISSUE TITLE
Problem with the delete button

### ISSUE THREAD

**Issue by siick** [KasperOlesen/DataTable-AltEditor#3]
Hello and first thanks for your work!
I'm trying to use the delete button for selected rows in my datatables.
I've got no problem to make it appears with my other buttons.
When i select a row and click on the delete button, the modal window appears but not with all my column titles, it's missing the first one. So i've changed on your code that line in the _openDeleteModal function.
`//Adding attribute IDs and values to object
         for( var i = 1; i < dt.context[0].aoColumns.length; i++ )`
to that
`//Adding attribute IDs and values to object
         for( var i = 0; i < dt.context[0].aoColumns.length; i++ )`
and now i've got all my titles in the modal window but i've got no data! There are all written to 'undefined'.
It seems it can't get the data from the object. I've tried to look into that object
 `dt.context[0].aoColumns[i].data`
 where you try to get the data but when i "console.log" dt.context[0].aoColumns[j] i can't see any data inside.
Here's a sample if it can help you to explain where is my data
`Object {idx: 3, aDataSort: Array(1), asSorting: Array(2), bSearchable: true, bSortable: true…}
aDataSort:Array(1)
asSorting:Array(2)
bSearchable:true
bSortable:true
bVisible:true
fnCreatedCell:null
fnGetData:function (a,b,c)
fnSetData:function (a,b,c)
iDataSort:-1
idx:3
mData:3
mRender:null
nTf:th.search
nTh:th.sorting
sCellType:"td"
sClass:""
sContentPadding:""
sDefaultContent:null
sName:""
sSortDataType:"std"
sSortingClass:"sorting"
sSortingClassJUI:""
sTitle:"Action"
sType:"html"
sWidth:"201px"
sWidthOrig:null
_bAttrSrc:false
_hungarianMap:Object
_sManualType:null
_setter:null
__proto__:Object`

Thanks in advance for your future answer.

**Comment by siick** [comment]
Ok i've found where is my data.
i've "console.log" dt.context[0] to find it, and i've found it here
`dt.context[0].aoData[x]._aFilterData[x]`
Try to fix it and bring an answer here ;)

**Comment by siick** [comment]
Ok i've found where is my problem!
`dt.context[0].aoColumns[i].data` is not trying to get data. I was confused by the undefined text writing in my modal window.
You try to get data on that line
`data += "<div class='form-group'><label for='" + columnDefs[j].title + "'>" + columnDefs[j].title + " : </label><input  type='hidden'  id='" + columnDefs[j].title + "' name='" + columnDefs[j].title + "' placeholder='" + columnDefs[j].title + "' style='overflow:hidden'  class='form-control' value='" + adata.data()[0][columnDefs[j].name] + "' >" + adata.data()[0][columnDefs[j].name] + "</input></div>";`
And now i get it work like that
`data += "<div class='form-group'><label for='" + columnDefs[j].title + "'>" + columnDefs[j].title + " : </label><input  type='hidden'  id='" + columnDefs[j].title + "' name='" + columnDefs[j].title + "' placeholder='" + columnDefs[j].title + "' style='overflow:hidden'  class='form-control' value='" + adata.data()[0][j] + "' >" + adata.data()[0][j] + "</input></div>";
`
It's just a problem for me? If not i can make a commit and a pull request.

**Comment by KasperOlesen** [comment]
Please commit your project so I can have a look.

**Comment by luca-vercelli** [comment]
closing as outdated
