### ISSUE TITLE
Datetimepicker can't pop up the calendar

### ISSUE THREAD

**Issue by YoYoAdorkable** [KasperOlesen/DataTable-AltEditor#32]
datetimepicker: { timepicker: false, format : "Y/m/d"}

Does this plugin support calendars?

**Comment by luca-vercelli** [comment]
Yes, that should work. What datepicker did you linked?

Il lun 1 lug 2019, 11:55 Hailong Yu <notifications@github.com> ha scritto:

**Comment by YoYoAdorkable** [comment]
I quote:
Demo.htmleaf.com/1706/201706191524/dist/js/bootstrap-datepicker.min.js
Http://demo.htmleaf.com/1706/201706191524/dist/locales/bootstrap-datepicker.zh-CN.min.js
Http://demo.htmleaf.com/1706/201706191524/dist/css/bootstrap-datepicker3.css

<script type="text/javascript">
         $(function(){
             $('.datepicker').datepicker({
                 Language: 'zh-CN'
             });
         })
</script>

Calendar can be popped up, click date can't be saved into form

**Comment by svanlaere** [comment]
Example with the datetimepicker did not work for me either, no pop up.

**Comment by luca-vercelli** [comment]
You are right, there's something broken :(

**Comment by luca-vercelli** [comment]
Issue should be solved. Can anybody confirm?
