### ISSUE TITLE
Editing Row correctly but not shown in Datatable 

### ISSUE THREAD

**Issue by DavidSelem** [KasperOlesen/DataTable-AltEditor#33]
When I try to edit a row I get a warning about request uknown parameters
![image](https://user-images.githubusercontent.com/7357354/60532349-ba052a80-9cc2-11e9-8d6b-5b30e7ef4b55.png)

I close the warning and the success alert appears under the form, but the data is inserted incorrectly
![image](https://user-images.githubusercontent.com/7357354/60532415-ddc87080-9cc2-11e9-9c07-4024dd17b7a6.png)

When I click on refresh the edited row appears now correctly
![image](https://user-images.githubusercontent.com/7357354/60532627-529baa80-9cc3-11e9-9144-8c0bc2281a6c.png)

This is the datatable data https://api.myjson.com/bins/19art7

This is the response of the edited row https://api.myjson.com/bins/107agj

This is my datatable conf: https://privatebin.net/?c12c9dbd5ca4f314#s9CMhq6kBfHW5ADkoq3YS43dq4BiYtYhZR+TOK+r6qk=

What am I doing wrong?

**Comment by luca-vercelli** [comment]
Hello, the JSON response must have a precise form. It should be

`{"NumEmpleado":2000,"correo":"eww@gmail.com","nombre":"Arturo Casanova","password":"password","perfilCompletado":1,"tipoCuenta":1}
`
and not 

`{"data":[{"NumEmpleado":2000,"correo":"eww@gmail.com","nombre":"Arturo Casanova","password":"password","perfilCompletado":1,"tipoCuenta":1}]}` 

If you really cannot change it, you should hack the method `_editRowCallback()`.

Please notice that your JSON response is quite strange. Why do you get an array? That array will always have length 1. I would prefer something like this:

`{"value":{"NumEmpleado":2000,"correo":"eww@gmail.com","nombre":"Arturo Casanova","password":"password","perfilCompletado":1,"tipoCuenta":1}}`

**Comment by DavidSelem** [comment]
I got it working: 

I changed the line 285 of dataTables.altEditor.free.js

that._editRowCallback(data,b,c,d,e);  to that._editRowCallback(rowDataArray,b,c,d,e); 



Complete section:
```
 that.onEditRow(that,
                    rowDataArray,
                    function(data,b,c,d,e){ that._editRowCallback(rowDataArray,b,c,d,e); },
                    function(data){ that._errorCallback(data);
                });
```

And now it doesn't show warnings and it refreshes as it should do

**Comment by luca-vercelli** [comment]
Well, yes, that's a trick. Not so good in my opinion. You are showing on the DataTable the data that the user has entered, not the data that the server returned. If the server (for some reason) modifies the user data, you cannot see that.

**Comment by luca-vercelli** [comment]
instead, you could try this:

```
 that.onEditRow(that,
                    rowDataArray,
                    function(data,b,c,d,e){ that._editRowCallback(data.data[0],b,c,d,e); },
                    function(data){ that._errorCallback(data);
                });
```

**Comment by luca-vercelli** [comment]
closing this old issue
