### ISSUE TITLE
Unable to hide input element with specified field type in the dialog modal

### ISSUE THREAD

**Issue by Alviansyah** [KasperOlesen/DataTable-AltEditor#35]
I recently tried using AltEditor. It's great, but i cannot disable/hide a specific input element that was shown in AltEditor modal unless i specified the field type to "readonly"/"hidden". I wanted that one element to be disabled or hidden but also able to specify its type as "text" or "number" like this:
```html
<input type="number" hidden>
```
or
```html
<input type="text" readonly>
```
Is there a possible way to do this?

**Comment by luca-vercelli** [comment]
I think that's not possibile. Can I ask why? Why should you change the type
of an input box, if nobody can change its value?

Il mar 16 lug 2019, 09:43 Alven RS <notifications@github.com> ha scritto:

**Comment by Alviansyah** [comment]
It affects operations that involve data type like, for example, sorting. Assume we have a table like this:

| ID        |
| ------------- |
| 1 | 
| 2 |
| 10 |
| 5 |
| 6 |
| 11 |

If we specify the field data type as hidden or readonly then sorting it down, the sorted data will become like this:

| ID        |
| ------------- |
| 1 | 
| 10 |
| 11 |
| 2 |
| 5 |
| 6 |

when the desired result is like this:

| ID        |
| ------------- |
| 1 | 
| 2 |
| 5 |
| 6 |
| 10 |
| 11 |

Those record are considered as text hence why the sorting algorithm cannot sort them in the way numbers are supposedly sorted. It will also affect the data type that we will receive from the editor. we will get text instead of number.

**Comment by luca-vercelli** [comment]
This is a good point. Unluckily some work is required. We should change the
behaviour of "read-only" flag.

Btw, I did not check, but I think that numbers in JSON data are *always*
sent as strings.

Il mer 17 lug 2019, 05:11 Alven RS <notifications@github.com> ha scritto:

**Comment by luca-vercelli** [comment]
I did some improvements on this subject. I have update the Readme, too. Could you please try it?

**Comment by Alviansyah** [comment]
Working as expected! https://jsfiddle.net/Alven/qn3s72gp/20/
Now i don't have to worry about accidentally changed the reference key(ID) in the modal dialog.
This plugin is great. Very beginner(like me) friendly. Thank you. Keep up the good works.

**Comment by luca-vercelli** [comment]
Thank you!
