### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by Edhant** [KasperOlesen/DataTable-AltEditor#36]
Hi, Can I  use this plugin for data extracted from MySQL via PHP?

**Comment by luca-vercelli** [comment]
I think so. You have to write a web service in PHP.

Luca

Il mar 16 lug 2019, 15:31 Edhant <notifications@github.com> ha scritto:

**Comment by Edhant** [comment]
ok, I built a web service in PHP (I have 4 files:
select, insert, update, delete) all return data:
echo json_encode ($ json);
Here everything works ok - I checked in ARC

I understand that you should use the solution from example 3. Can you support me and indicate what needs to be changed?

**Comment by luca-vercelli** [comment]
Referring to
https://github.com/KasperOlesen/DataTable-AltEditor/blob/master/example/03_ajax_objects/example3.js

You have to change, at least, the following:

* The columns definition, rows 3-31
* The URL of your "select" ws, row 36

So far, you should be able to see your datatable.

Then, you should create functions to handle update, delete, insert, rows
69-97
For example, for "insert", you should adapt rows 72-73.


Il mer 17 lug 2019, 15:46 Edhant <notifications@github.com> ha scritto:

**Comment by Edhant** [comment]
Thank for your help, everything works :-)

**Comment by Conny64** [comment]
> 
> 
> Thank for your help, everything works :-)
Hi @Edhant, 
I have the same problem. Please can you post your  soloution or contact me by mail 
conny.de@gmx.de

**Comment by TwinMist** [comment]
can someone post a demo of mysql please

thanks

**Comment by luca-vercelli** [comment]
In what language? PHP? You may find dozen of results for "crud PHP mySQL".
E.g.  https://github.com/chapagain/crud-php-simple of course you must adapt
it for altEditor

Il mar 6 lug 2021, 16:34 TwinMist ***@***.***> ha scritto:

**Comment by TwinMist** [comment]
Yes in php, 
would be you able to create a mysql demo example in php for us please
i like the look of your layout
thanks

**Comment by luca-vercelli** [comment]
Sorry, I have no time for this now. I haven't used this plugin for a while.


Il mar 6 lug 2021, 17:17 TwinMist ***@***.***> ha scritto:
