### ISSUE TITLE
cannot populate datatable using example 3

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#37]
HI,
    var tableActivitySettings = $('#datatableActivitySettings')
                .DataTable({ // Call a table function to create table.
                    "processing": true,
                    "lengthChange": false,
                    "pageLength": 50,
                    ajax: {
                        "url": Xrm.Page.context.getClientUrl() +
                            "/api/data/v8.2/ssi_activitysettings?$select=createdon,ssi_activitysettingid,ssi_availableinactivitiesplus,ssi_cancreateinactivitiesplus,ssi_entityname,ssi_includewithlastcontactedon,ssi_lastcontactedonattribute,ssi_lastcontactedonfieldtype,ssi_suppress",
    
                        "dataType": 'json',
                        "type": "GET",
                        "cache": true,
                        "beforeSend": function (XMLHttpRequest) {
                            XMLHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
                            XMLHttpRequest.setRequestHeader("OData-Version", "4.0");
                            XMLHttpRequest.setRequestHeader("Accept", "application/json");
                            XMLHttpRequest.setRequestHeader("Prefer", "odata.include-annotations=\"*\"");
                        },
                        "async": false,
                        "complete": function (json, type) { //type return "success" or "parsererror"
                            if (type == "parsererror") {
                                alert("parsererror");
                            } else {
                                //alert("from Complete: "+json);
    
                            }
                        },
                        "dataSrc": function (json) {
                            arrDataActivitySettings = [];
                            arrItems = [];
                            // Convert Json data into 2-d Array
                            //ssi_activitiespluscolumnid,ssi_columnheading,ssi_columntype,ssi_columnwidth,ssi_commonattributename,ssi_customattributetype,ssi_displayorder,ssi_sortcolumn,ssi_sortdirection
                            $.each(json.value, function (index, value) {
                                arrItems.push(value.ssi_activitysettingid);
                                arrItems.push(value
                                    .ssi_entityname
                                ); //["ssi_columntype@OData.Community.Display.V1.FormattedValue"]);
                                arrItems.push(value[
                                    "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue"
                                ]); //
                                arrItems.push(value[
                                    "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue"
                                ]);
                                arrItems.push(value[
                                    "ssi_lastcontactedonattribute@OData.Community.Display.V1.FormattedValue"
                                ] == null ? "Null" : value[
                                    "ssi_customattributetype@OData.Community.Display.V1.FormattedValue"
                                ]);
                                arrItems.push(value[
                                    "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue"
                                ]);
                                arrItems.push(value[
                                    "ssi_suppress@OData.Community.Display.V1.FormattedValue"
                                ]);
                                arrItems.push(value[
                                    "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue"
                                ]);
                                arrItems.push(value[
                                    "createdon@OData.Community.Display.V1.FormattedValue"]);
                                arrDataActivitySettings.push(
                                    arrItems
                                ); // Push The Values Inside the Array to Create 2-D Array
    
                                arrItems = [];
                            });
    
                            return arrDataActivitySettings;
                        }
    
                    },
                    'data': arrDataActivitySettings,
                    'columnDefs': [{
                        'targets': 0,
                        'searchable': false,
                        'orderable': false,
                        'width': '1%',
                        'className': 'dt-body-center',
                        'render': function (data, type, full, meta) {
                            return '<input type="checkbox">';
                        }
                    }],
    
                    'order': [1, 'asc'],
                    'rowCallback': function (row, data, dataIndex) {
                        // Get row ID
                        var rowId = data[0];
    
                        // If row ID is in the list of selected row IDs
                        if ($.inArray(rowId, rows_selected) !== -1) {
                            $(row).find('input[type="checkbox"]').prop('checked', true);
                            //$(row).addClass('selected');
                        }
                    },
    
                    'initComplete': function () {
                        
                    }
    
                });

Above is the code I used to populate datatble from dynamics crm,
Below is the result from webapi call

 "@odata.context": "http://devarcrm82/CrmPlusCoreDevV2/api/data/v8.2/$metadata#ssi_activitysettings(_createdby_value,ssi_availableinactivitiesplus,ssi_cancreateinactivitiesplus,ssi_entityname,ssi_includewithlastcontactedon,ssi_lastcontactedonattribute,ssi_lastcontactedonfieldtype)",
    "value": [
        {
            "@odata.etag": "W/\"528951\"",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "SYSTEM",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value": "b5655f68-b549-46a3-8b9f-e371e21e75ab",
            "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_availableinactivitiesplus": true,
            "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_cancreateinactivitiesplus": true,
            "ssi_entityname": "bulkoperation",
            "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_includewithlastcontactedon": false,
            "ssi_lastcontactedonattribute": null,
            "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue": "Activity Type",
            "ssi_lastcontactedonfieldtype": true,
            "ssi_activitysettingid": "7667117d-3c92-e911-aa24-060dfd5b0b84"
        },
       
        {
            "@odata.etag": "W/\"528956\"",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "SYSTEM",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value": "b5655f68-b549-46a3-8b9f-e371e21e75ab",
            "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_availableinactivitiesplus": true,
            "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_cancreateinactivitiesplus": true,
            "ssi_entityname": "task",
            "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_includewithlastcontactedon": false,
            "ssi_lastcontactedonattribute": null,
            "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue": "Activity Type",
            "ssi_lastcontactedonfieldtype": true,
            "ssi_activitysettingid": "7b67117d-3c92-e911-aa24-060dfd5b0b84"
        },
        {
            "@odata.etag": "W/\"528957\"",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "SYSTEM",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value": "b5655f68-b549-46a3-8b9f-e371e21e75ab",
            "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_availableinactivitiesplus": true,
            "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_cancreateinactivitiesplus": true,
            "ssi_entityname": "incidentresolution",
            "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_includewithlastcontactedon": false,
            "ssi_lastcontactedonattribute": null,
            "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue": "Activity Type",
            "ssi_lastcontactedonfieldtype": true,
            "ssi_activitysettingid": "7c67117d-3c92-e911-aa24-060dfd5b0b84"
        },
        {
            "@odata.etag": "W/\"528958\"",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "SYSTEM",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value": "b5655f68-b549-46a3-8b9f-e371e21e75ab",
            "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_availableinactivitiesplus": true,
            "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue": "Yes",
            "ssi_cancreateinactivitiesplus": true,
            "ssi_entityname": "campaignresponse",
            "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_includewithlastcontactedon": false,
            "ssi_lastcontactedonattribute": null,
            "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue": "Activity Type",
            "ssi_lastcontactedonfieldtype": true,
            "ssi_activitysettingid": "7d67117d-3c92-e911-aa24-060dfd5b0b84"
        },
      
        {
            "@odata.etag": "W/\"536735\"",
            "_createdby_value@OData.Community.Display.V1.FormattedValue": "Aparna Ravidas",
            "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
            "_createdby_value": "37a4ef55-0191-e911-aa24-060dfd5b0b84",
            "ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_availableinactivitiesplus": false,
            "ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_cancreateinactivitiesplus": false,
            "ssi_entityname": " test name",
            "ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue": "No",
            "ssi_includewithlastcontactedon": false,
            "ssi_lastcontactedonattribute": "test field",
            "ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue": "Activity Attribute",
            "ssi_lastcontactedonfieldtype": false,
            "ssi_activitysettingid": "9d46e4b5-acac-e911-aa25-060dfd5b0b84"
        }
    ]
}
How can example be modified to populate this values to the datatable. Thanks in advance

**Comment by luca-vercelli** [comment]
I don't undestand if your question is about the AltEditor, or about Datatables.

If you just need to populate a Datatable, you should better ask on [its forum](https://datatables.net/forums/discussions)

Later you can add AltEditor functionalities, if needed.

**Comment by aparnasravidas** [comment]
Thank You ... i did it by using dataSrc after pushing it to an array.  would you please help me with the delete functionality .  how can  a particulalar field be extracted from rowdata?? thanks in advance

**Comment by aparnasravidas** [comment]
> I don't undestand if your question is about the AltEditor, or about Datatables.
> 
> If you just need to populate a Datatable, you should better ask on [its forum](https://datatables.net/forums/discussions)
> 
> Later you can add AltEditor functionalities, if needed.

Thank u .. fixed it using dataSrc as an array
