### ISSUE TITLE
Update column options after choosing an option in a select.

### ISSUE THREAD

**Issue by dpfernandez10** [KasperOlesen/DataTable-AltEditor#38]
Hi, is there any way to update column options after choosing an option in a select?
For example:

            table = $('#table').DataTable({
                dom: "Bfrtip",
                ajax: {
                    url: urlHOST + myEndponit,
                    type: 'GET'
                },
                columns: [
                    { data: "id", type: "hidden" },
                    { data: "accountId", type: "select", options: accountsData },
                    { data: "projectId", type: "select", options: projectsData },
                    { data: "wbsId", type: "select", options: wbsData }
                ]

I have two calls to api that load the accounts and the projects, but I need that when selecting an account this one load another list of projects that belong to that account, the call to the api is prepared.

Is there something like a function for the options in which can update the options with an onchange?

Regards.

**Comment by luca-vercelli** [comment]
no, this is not supported (so far)
