### ISSUE TITLE
dropdownlist not working

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#40]
HI 
created a dropdownlist as follows in the table function to create table
     columnDefs: [{
      type: "select",
      "targets": 7,
     
    options : optionselection,
    select2 : { width: "100%"},
    render: function (data, type, row, meta) {
        if (data == null || !(data in optionselection)) return null;
        return optionselection[data];
      }
    }],

where var times is declared
as  var optionselection= {Yes: "Yes", No:"No"}
But in the model it shows a field as highlighted , which changes on changing the dropdownlist value.  Could anyone provide a solution for this please. Thanks in advance

**Comment by aparnasravidas** [comment]
![image](https://user-images.githubusercontent.com/11177392/62076586-05edb580-b216-11e9-80c5-7124793cb9b4.png)

**Comment by aparnasravidas** [comment]
![image](https://user-images.githubusercontent.com/11177392/62077440-16069480-b218-11e9-9241-cd427c0e00ee.png)

**Comment by luca-vercelli** [comment]
This seems an issue of the `select2`. Did you include all necessary dependencies? both .css and .js, with right versions? Did you try to use a normal `select` instead of a `select2` (just comment the `select2` option line)?

**Comment by aparnasravidas** [comment]
Thank you so much for the response.   It was resolved when css was included..
