### ISSUE TITLE
in the edit modal, dropdowns not showing the selected option

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#41]
Hi, In the edit dialog, even though its fetching the correct rowdata, the dropdownlist is showing the first option instead
d of the selected option. PLease help. Thank U in advance

![image](https://user-images.githubusercontent.com/11177392/62153248-2713dc00-b2d2-11e9-9e37-1d8109fe4717.png)

**Comment by aparnasravidas** [comment]
Instead of entity name "campaign response", the first option "bulk operation is shown". But the id confirms that it point to the correct row

**Comment by aparnasravidas** [comment]
var optionActivitySettingsEntityName = {
    "bulkoperation": "Bulk Operation",
    "campaignactivity": "Campaign Activity",
    "untrackedemail": "Untracked Email",
    "email": "Email",
    "recurringappointmentmaster": "Recurring Appointment",
    "task": "Task",
    "incidentresolution": "Case Resolution",
    "campaignresponse": "Campaign Response",
    "fax": "Fax",
    "opportunityclose": "Opportunity Close",
    "serviceappointment": "Service Activity",
    "letter": "Letter",
    "orderclose": "Order Close",
    "appointment": "Appointment",
    "socialactivity": "Social Activity",
    "quoteclose": "Quote Close",
    "phonecall": "Phone Call"
  }

datatable is populated using datasrc
  dataSrc: function (json) {
        arrDataActivitySettings = [];
        arrItems = [];
        // Convert Json data into 2-d Array
        //ssi_activitiespluscolumnid,ssi_columnheading,ssi_columntype,ssi_columnwidth,ssi_commonattributename,ssi_customattributetype,ssi_displayorder,ssi_sortcolumn,ssi_sortdirection
        $.each(json.value, function (index, value) {
          value.ssi_
          arrItems.push(value.ssi_activitysettingid);
          arrItems.push(value.ssi_entityname);
          arrItems.push(value["ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue"] == null ? "-" : value["ssi_availableinactivitiesplus@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value["ssi_suppress@OData.Community.Display.V1.FormattedValue"] == null ? "" : value["ssi_suppress@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value["ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue"] == null ? "-" : value["ssi_cancreateinactivitiesplus@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value["ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue"] == null ? "-" : value["ssi_includewithlastcontactedon@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value["ssi_lastcontactedonattribute@OData.Community.Display.V1.FormattedValue"] == null ? "-" : value["ssi_lastcontactedonattribute@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value["ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue"] == null ? "-" : value["ssi_lastcontactedonfieldtype@OData.Community.Display.V1.FormattedValue"]);
          arrItems.push(value.createdon);

          arrDataActivitySettings.push(arrItems); // Push The Values Inside the Array to Create 2-D Array

          arrItems = [];
        });
        alert(arrDataActivitySettings);
        return arrDataActivitySettings;
      }

and dropdown is rendered
 columnDefs: [{
        "targets": [0],
        "visible": false,
        "searchable": false
      },
      {
        type: "select",
        "targets": 1,
        options: optionActivitySettingsEntityName,
        select2: {
          width: "100%"
        },
           
        render: function (data, type, row, meta) {
          if (data == null || !(data in optionActivitySettingsEntityName)) return null;
          return optionActivitySettingsEntityName[data];
          
        }
      },
      {     
        type: "select",
        "targets": 2,
        options: optionActivitySettingsSelection,
        select2: {
          width: "100%"
        },
        render: function (data, type, row, meta) {
          if (data == null || !(data in optionActivitySettingsSelection)) return null;
          return optionActivitySettingsSelection[data];
        }
      },

**Comment by aparnasravidas** [comment]
_openEditModal: function () {
                
                var dt = this.s.dt;
                var adata = dt.rows({
                    selected: true
                });
                
                var columnDefs = this.completeColumnDefs();
                var data = this.createDialog(columnDefs, 'Edit Record', 'Edit', 'Close', 'editRowBtn');

                var selector = this.modal_selector;
                
                for (var j in columnDefs) {
                    var arrIndex = "['" + columnDefs[j].name.toString().split(".").join("']['") + "']";
                    var selectedValue = eval("adata.data()[0]" + arrIndex);
                    alert(selectedValue);

It alerts the correct row chosen to edit, but dropdowns does not show the selected value. Please help

**Comment by luca-vercelli** [comment]
Yes, I confirm the issue.

**Comment by luca-vercelli** [comment]
OK, I have introduced this issue with PR #34.  It seems that "select2" and "datetimepicker" are different, they require different handling.
The easy way to solve the issue is to add the two lines that I have removed here:

[https://github.com/KasperOlesen/DataTable-AltEditor/pull/34/commits/3fc17643f9546adf3f3b12b68f28d4d7310c2db7](https://github.com/KasperOlesen/DataTable-AltEditor/pull/34/commits/3fc17643f9546adf3f3b12b68f28d4d7310c2db7
)
However, that way the datetimepickers will not work.

**Comment by aparnasravidas** [comment]
Thank You so much.. It worked.. with the fix you suggested

**Comment by luca-vercelli** [comment]
I open again the issue... searching for a better solution

**Comment by luca-vercelli** [comment]
Found a better solution, just trigger "change" event on the select2
