### ISSUE TITLE
creation "add and continue" and "add and close" button on modal editing

### ISSUE THREAD

**Issue by mdemori** [KasperOlesen/DataTable-AltEditor#43]
Hi,

there is a method to add two different button on modal edit? 
I need an "add and continue" that simply add the record and reset the form and another one like "add and close" that add the row and close the modal if there are no errors

There are some options that I miss or is something that I must add by myself?

Thank you for you awesome extension!

**Comment by luca-vercelli** [comment]
Unluckily no, there is nothing as such.
You should modify at least the `_setup()` and `createDialog()` functions to add a new button.
