### ISSUE TITLE
adding js event to modal form fields

### ISSUE THREAD

**Issue by mdemori** [KasperOlesen/DataTable-AltEditor#44]
Hello, 

after creating the modal, I need to set-up some event on some input fields. There is a way to add a callback function after modal has been created?

thank you

**Comment by luca-vercelli** [comment]
There is nothing as such so far.
I guess you can add some custom jquery event where you need it.
For example, you may change th `_openAddModal()` function, at the end you may add something like this:

    $(selector).trigger("alteditor:dialog_was_open");

and in your code you may catch such event.
This is just an idea, let me know if it works.
