### ISSUE TITLE
Call _openEditModal from another button.

### ISSUE THREAD

**Issue by dpfernandez10** [KasperOlesen/DataTable-AltEditor#45]
Hi, i'm implementing a right click context menu, the idea is select a row, right click and choose edit or delete like the main buttons.
How i can imitate the buttons fuctions?

Regards.

**Comment by luca-vercelli** [comment]
Your methods should just call the `_openDeleteModal()` or `_openEditModal()` methods otf the datatable, everything should work

**Comment by luca-vercelli** [comment]
Please see https://luca-vercelli.github.io/DataTable-AltEditor/example/12_inline_buttons/example12.html
