### ISSUE TITLE
How to customize the modal based on the datatable input

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#48]
Hi,
in the below code,datatable is populated by json. modal popsup with add, edit , delete functionalities works fine.javascript objects are used to populate dropdownlists.

var optionActivityColumnsColumnType = {
        "true": "Entity Specific Attribute",
        "false": "Common Attribute"
    }  
    var url_activitycolumns_get = "xxxxx/api/data/v8.2/ssi_activitiespluscolumns? 
    $select=.....,ssi_commonattributename,ssi_customattributetype,....";

    TableActivityColumns = $('#datatableActivityColumns').DataTable({
        "sPaginationType": "full_numbers",
        ajax: {
            url: url_activitycolumns_get,
            dataType: 'json',
            type: "GET",
            cache: true,
            beforeSend: function (XMLHttpRequest) {
                XMLHttpRequest.setRequestHeader("OData-MaxVersion", "4.0");
                XMLHttpRequest.setRequestHeader("OData-Version", "4.0");
                XMLHttpRequest.setRequestHeader("Accept", "application/json");
                XMLHttpRequest.setRequestHeader("Prefer", "odata.include-annotations=\"*\"");
                XMLHttpRequest.setRequestHeader("Prefer", "odata.include-annotations=\"OData.Community.Display.V1.FormattedValue\"");
            },
            async: false,
            complete: function (json, type) { //type return "success" or "parsererror"
                if (type == "parsererror") {
                    alert("parsererror");

                } else {

                }
            },
            dataSrc: function (json) {
                arrDataActivityColumns = [];
                arrItems = [];
                // Convert Json data into 2-d Array               
                $.each(json.value, function (index, value) {
                 arrItems.push(value.ssi_activitiespluscolumnid);
                    arrItems.push(value.ssi_columnheading);
                    arrItems.push(value["ssi_columntype"] == null ? "null" : value["ssi_columntype"]);
                    arrDataActivityColumns.push(arrItems); // Push The Values Inside the Array to Create 2-D Array
                    arrItems = [];
                });

                return arrDataActivityColumns;
            }
        },
        columnDefs: [{
                type: "hidden",
                "targets": [0],
                "visible": false,
                "searchable": false
            },
            {
                type: "select",
                "targets": 2,
                options: optionActivityColumnsColumnType,
                select2: {
                    width: "100%"
                },
                render: function (data, type, row, meta) {
                    alert(data);
                    if (data == null || !(data in optionActivityColumnsColumnType)) return null;
                    return optionActivityColumnsColumnType[data];

                }
            },

As you can see in the columnDef , target 2 uses a javascript object optionActivityColumnsColumnType, which is being used to get the datasrc json value of ssi_columntype.
what I want to do is , if the value is true, some fields in the modal should be hidden .

Could some one please help me with this requirement. Thanks in Advance

**Comment by luca-vercelli** [comment]
I'm afraid there is nothing as such.

Anyway, I think that you could reach your goal with some jquery trigger.

Something like this: 

    $(yourdatatable).on('change', 'the-input-field-that-you-want-to-watch', function(obj) {
        if (obj.value == true)
             $(the-other-field-that-you-want-to-hide).hide()
        else
             $(the-other-field-that-you-want-to-show).show()
        });

**Comment by aparnasravidas** [comment]
Hi, still I cannot figure out, The add or edit dialog is created based on the columndef. So the fields are dynamic. My requirement is if a particular  cell data in column 2 is true, hide field in the edit dialog corresponding to column 8. My assumption was to alter the alteditor js .  createDialog: function (columnDefs, title, buttonCaption, closeCaption, buttonClass) . Please guide if its wrong or if there is a better solution for it.
Thank you

**Comment by luca-vercelli** [comment]
Did you find a solution for this? If not, and you are still interested, you should create some minimal example on fiddlejs.
