### ISSUE TITLE
Can't call _openEditModal() from another .js

### ISSUE THREAD

**Issue by carlostcsilva** [KasperOlesen/DataTable-AltEditor#49]
Your methods should just call the `_openDeleteModal()` or `_openEditModal()` methods of the datatable, everything should work

_Originally posted by @luca-vercelli in https://github.com/KasperOlesen/DataTable-AltEditor/issues/45#issuecomment-523424511_

I've tried calling it from another .js, but I'm gettin a reference error.
Can I have an example on how to use this from another .js?

**Comment by luca-vercelli** [comment]
Could you be a little more precise? are you still trying to create a context menu? what exactly did you try so far?

**Comment by carlostcsilva** [comment]
Sorry,

I want to do the same thing as the guy in the issue#45, call the _openEditModal from another button.

So far, I've tried calling it directly on another function. I've searched on how to call a function within a prototype, with no success. 

Sorry if this isn't very helpful.

**Comment by luca-vercelli** [comment]
You cannot call it on a prototype, you must have a datatable object. For
example, if you define the datatable as

    var mydatatable = $(mytable).Datatable() .....


Then you should call

    mydatatable._openEditModal()

Honestly I don't remember how to access the same js variables across
different js files.



Il lun 2 set 2019, 22:49 carlostcsilva <notifications@github.com> ha
scritto:

**Comment by carlostcsilva** [comment]
Calling it from the datatable didn't work.

I'll keep trying to find a solution, and if I find it, I'll post it here and close the issue.

If you find anything, please let me know.

**Comment by luca-vercelli** [comment]
You are right, the datatable object is more complicated than I thought.
What about this:

    myTable.button('add:name').trigger('click')

?

**Comment by luca-vercelli** [comment]
I have added a reference to the internal object, so now you should be able to call this:

    $('#mytableid').altEditor._openAddModal()

**Comment by carlostcsilva** [comment]
Sorry for the delay.

Thank you very much, now it's working.
Just so you know, I had to call it like this:

$('#tableId')[0].altEditor._openAddModal();

**Comment by luca-vercelli** [comment]
For the records,

    var that = $('#tableId')[0].altEditor;
    that._openAddModal();
     $('#altEditor-add-form-' + that.random_id)
                        .off('submit')
                        .on('submit', function (e) {
                            e.preventDefault();
                            e.stopPropagation();
                            that._addRowData();
                        });
