### ISSUE TITLE
Datatables didn't find DT_RowId

### ISSUE THREAD

**Issue by PaSch1** [KasperOlesen/DataTable-AltEditor#5]
Hi,

i need some help. :) Datatables didn't find DT_RowId in my table.

My Datatable works in server-side mode. The syntax of my received JSON(array) is: 
[["3","email@sample.ca"],["6","email@sample.ca"]

Thereby columns:[{...,data: "DT_RowId",...}] can be found, did i need a JSON (object) like
[{"DT_RowId":"3", "Email":"email@sample.ca"}] ?

Greetings
Patrick

**Comment by PaSch1** [comment]
I don't know why i can't access the row by name. But with the direct number and a JSON(array) it works. :)
id: "NiceApp",
title: "go on",
data: 3,
....

**Comment by luca-vercelli** [comment]
Closing as DT_RowId is obsolete now
