### ISSUE TITLE
Edit row functions not able to reference to datatable

### ISSUE THREAD

**Issue by bitrevo** [KasperOlesen/DataTable-AltEditor#52]
The `dt` param should reference to the datatable, however, currently it is reference to `altEditor` object.

```
onAddRow: function(dt, rowdata, success, error) {
	console.log(dt);
},
```
```
altEditor {c: {…}, s: {…}, dom: {…}, onAddRow: ƒ, onEditRow: ƒ, …}
```

**Comment by luca-vercelli** [comment]
You are right.
Unluckily I have no idea how to solve it. The "altEditor" object is passed at line 589; at that point, I don't know how to get the Datatable object. If you have only one Datatable in your page, you may still retrieve it in common ways.

**Comment by bitrevo** [comment]
Seems like we can get the datatable object by `dt.s.dt.table().node()`.

**Comment by luca-vercelli** [comment]
Ok, I got it. This is not a bug, it's an intended feature. You get the datatable object using `dt.s.dt`. I will update docs.
