### ISSUE TITLE
Ordering select field items

### ISSUE THREAD

**Issue by rafalito666** [KasperOlesen/DataTable-AltEditor#58]
Y populated a Select field with json. I need this order
{"5":"AAAAA", "4":"BBBBB", "3":"CCCCC", "2":"DDDDD", "1":"EEEEE", }
but, in modal editor, items are reordered and shows as 
1: EEEEEE
2: DDDDD
.....
........

**Comment by luca-vercelli** [comment]
Maybe you could debug lines 468-471. That's where the select is populated.

Il giorno dom 29 set 2019 alle ore 14:00 rafalito666 <
notifications@github.com> ha scritto:

**Comment by luca-vercelli** [comment]
any news on this?
