### ISSUE TITLE
Add more events to add button

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#59]
Hi,
According to the requirements. I have 6 different datatables on different tabs on same html page which make use of the same file datatables.AltEditor.free.js. I have 6 different .js files to maintain each of these datatables. As shown below
![image](https://user-images.githubusercontent.com/11177392/66214488-ccab4900-e68f-11e9-8297-4a1af78bfdef.png)
![image](https://user-images.githubusercontent.com/11177392/66214574-f5cbd980-e68f-11e9-8d54-e52b8978fbbc.png)

Now  the current requirement, is in the 2nd tab alone, on clicking the add button, along with the _openAddModal: function, it has to fetch some json data and populate it in the dropdown in modal. ie it need to add more functions in the corresponding .JS file along with the _openAddModal function in the datatables.AltEditor.free.js file. 

Can anybody please help me solve this issue. THank you in advance

**Comment by luca-vercelli** [comment]
This is an old issue, did you solve your problem?
