### ISSUE TITLE
Inputvalidation doesn't work

### ISSUE THREAD

**Issue by PaSch1** [KasperOlesen/DataTable-AltEditor#6]
If someone else has the problem. I have changed the following line.
old:

> 731:  }else if($(this).attr("data-special") != "portRange" && !$(this).context.checkValidity()){

> 731:  }else if($(this).attr("data-special") != "portRange" && !$(this)[0].checkValidity()){

**Comment by AndrewBuiltThis** [comment]
Are you able to use form-validation with this? I haven't been able to support anything beyond the 'text' and 'readonly' types ... I'm looking to implement some radio buttons, some drop-down lists and basic input validation, but I haven't seen that done -- have you?
