### ISSUE TITLE
How to set a default value in dropdown?

### ISSUE THREAD

**Issue by Terumi** [KasperOlesen/DataTable-AltEditor#63]
Is it possible when you try to edit a row, the modal to appear with the value of the select fields prepopulated?

**Comment by luca-vercelli** [comment]
When you *edit* or when you *add* a row? When you edit the row, the current
value should be pre-selected.

Il lun 4 nov 2019, 18:56 Tasos Protopapas <notifications@github.com> ha
scritto:

**Comment by Terumi** [comment]
When you edit a row, if you have provided options to the select field, it doesnt show the one on the database.

**Comment by luca-vercelli** [comment]
Yes, it should.
You can see this for example:

https://luca-vercelli.github.io/DataTable-AltEditor/example/04_more/DataTableExample.html

or this


Il giorno lun 4 nov 2019 alle ore 20:02 Tasos Protopapas <
notifications@github.com> ha scritto:

**Comment by Terumi** [comment]
It works only if the options array contains a single value.
If I populate the table with say company names, I won't be able to have an accompanying company_id as a value.

**Comment by luca-vercelli** [comment]
I think you may have some conflict in the versions of your libraries, jquery and/or datatable and/or select2

**Comment by luca-vercelli** [comment]
any news on this?
