### ISSUE TITLE
Validation in Select

### ISSUE THREAD

**Issue by aparnasravidas** [KasperOlesen/DataTable-AltEditor#64]
How do we check if the select has no value selected and prevent the form from being submitted?
This is the columndef for the select and is populated from json and is tied up with editorOnChange() event also

  {
                type: "select",
                "targets": 2,
                options: optionHierarchyName,
                select2: {
                    width: "100%"
                },

                editorOnChange: function (event, altEditor) {
                    console.log(event, altEditor);
                    var curEntityNameHS = $(event.currentTarget).val();
                    var primarytempHS = {};
                    var secondarytempHS = {};
                    primarytempHS = getPrimaryAttributesHS(curEntityNameHS);
                    secondarytempHS = getSecondaryAttributesHS(curEntityNameHS);
                    (JSON.stringify(primarytempHS));
                    $(altEditor.modal_selector).find("#alteditor-row-3").show();
                    var temp1 = $(altEditor.modal_selector).find('#3');
                    altEditor.reloadOptions(temp1, primarytempHS);
There will be situation that there wont be any options in the select to chose. If no  select option is choosed, validation should prevent the form submission. 
Is ther a way to achieve that.

Thank You in advance

**Comment by luca-vercelli** [comment]
This is weird. It seems that nobody has ever thought to some kind of "required" column option.
Best idea should be to implement that.
