### ISSUE TITLE
Visible option does not function properly

### ISSUE THREAD

**Issue by xibriz** [KasperOlesen/DataTable-AltEditor#65]
When using `visible: false` in a `columDef`, the Colum Header text is hidden, but not the value in the modals.

The example `04_more` shows this error in the ID field.
In the modals for Add, Edit and Delete, the text `DT_RowId` is hidden, but the corresponding value/input is shown.

**Comment by luca-vercelli** [comment]
You could change the input type in "hidden" to hide it

This is the relevant piece of code of your interest:

https://github.com/KasperOlesen/DataTable-AltEditor/blob/1e008fb704e70f21fe80df4cc7f8a86bb1a3dd13/src/dataTables.altEditor.free.js#L435

**Comment by xibriz** [comment]
Thanks, it works.
