### ISSUE TITLE
HTML Required attribute

### ISSUE THREAD

**Issue by xibriz** [KasperOlesen/DataTable-AltEditor#66]
It would be nice to have the HTML Required attribute available on input fields to take advantage of browser validation of inputs.

https://www.w3schools.com/tags/att_input_required.asp

**Comment by luca-vercelli** [comment]
Yes, this is similar to issue #64 . Feel free to volunteer!

**Comment by luca-vercelli** [comment]
If you look at my repository, I just did a commit:

https://github.com/luca-vercelli/DataTable-AltEditor/blob/master/src/dataTables.altEditor.free.js

With this new feature, you can pass a new parameter "required:true" to column, and the tag "required" appears on the form.
However, I don't know how to activate the "browser validation of inputs". Do you have any idea?

**Comment by xibriz** [comment]
You don't have do to anything other than add the `required` attribute to the input. When submiting a form the browser will alert the user if the input is empty.

ref https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_required

**Comment by luca-vercelli** [comment]
Unluckily, we are not submitting any form. When the user press the "Add" or "Edit" button, we send data via AJAX to some webservice, so the validation is bypassed.
You can see an example here:

https://luca-vercelli.github.io/DataTable-AltEditor/example/01_in_memory_arrays/example1.html

the field "Name" has the "required" option set, however validation does not work.

**Comment by xibriz** [comment]
A quick google search gives us the answer :) 

https://stackoverflow.com/questions/43162858/will-jquery-or-ajax-make-html-required-attribute-invalid

**Comment by luca-vercelli** [comment]
Please, could you check it now?

**Comment by xibriz** [comment]
I found a couple of bugs. Will share later today or tomorrow.
