### ISSUE TITLE
Multi-Select / Edit

### ISSUE THREAD

**Issue by irreleph4nt** [KasperOlesen/DataTable-AltEditor#67]
Hi,

Is it possible to edit multiple rows at once with this editor? Meaning, can I enable somehow that a user selects multiple rows and when they press "Edit", columns with varying values show something like "Multiple Values"? The idea is to be able to set column A of rows 1 and 3 to the same value through one operation.

**Comment by luca-vercelli** [comment]
No, this is not supported.

Il mer 13 nov 2019, 19:01 irreleph4nt <notifications@github.com> ha scritto:

**Comment by ericorain** [comment]
Hi.

I just discovered DataTable-AltEditor. Is planned to add delete/edit multiple selection lines feature in future releases? Deleting many lines instead of one by one would be a great improvement for this software.
