### ISSUE TITLE
Pattern not working

### ISSUE THREAD

**Issue by gavinsin0001** [KasperOlesen/DataTable-AltEditor#72]
After recent "required" flag commit, my pattern checking is NOT working anymore. Why remove the validate function?

**Comment by luca-vercelli** [comment]
The validation should be performed by browser directly.

Maybe your pattern content is not HTML5-compatible? What did you write 
inside it?


Il 22/11/2019 10:42, gavinsin0001 ha scritto:

**Comment by gavinsin0001** [comment]
My previous patterns are for ID number (pattern:"^\\S+\\(\\S\\)$"), phone number (pattern:"^\\d{8,13}$") and email (pattern: "^\\S+\\@\\S+$").

Are they not HTML5-compatible?

And so we cannot have custom error message then.

**Comment by luca-vercelli** [comment]
I think you should remove the trailing "?" and "$". Can you try?

Moreover, yes, you can have custom error messages, see e.g. 
https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation

I understand this breaks old AltEditor's, however this approach is more 
standard nowadays. Maybe can you guess some form of 
backward-compatibility ?


Il 22/11/2019 11:35, gavinsin0001 ha scritto:

**Comment by gavinsin0001** [comment]
Seems removing the trailing "$" works. Thanks.
