### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by LucasGll** [KasperOlesen/DataTable-AltEditor#73]
I was wondering how you translate, the language

in my case I will translate to portuguese brazil

**Comment by luca-vercelli** [comment]
I have just created an example here
https://luca-vercelli.github.io/DataTable-AltEditor/example/09_translations/example9.html

If you do some translation, you could pull it here :
https://github.com/KasperOlesen/DataTable-AltEditor/tree/master/translations

**Comment by LucasGll** [comment]
very good!
