### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by LucasGll** [KasperOlesen/DataTable-AltEditor#75]
how do I validate and handle messages coming from php, I find it safer

For example, if in case of an error the message returns no success or error and will be displayed on the screen!

![Capturar](https://user-images.githubusercontent.com/42121382/70049050-92382c80-15aa-11ea-8b86-e203d2cb2cdd.PNG)

I am able to register, editing by php file, but I need to do some validations in my file, if there is an error I want to display on the screen

**translated by google translator**

**Comment by luca-vercelli** [comment]
Hello, this is an old question, was the issue solved?
A similar question was posted here https://github.com/KasperOlesen/DataTable-AltEditor/issues/79
