### ISSUE TITLE
Absence of textarea type

### ISSUE THREAD

**Issue by Madpixel6** [KasperOlesen/DataTable-AltEditor#76]
The input type using textarea is missing, it would be really nice if you could add it.

**Comment by taewookim** [comment]
Same request.

ARe there any workarounds currently?

**Comment by luca-vercelli** [comment]
No, this is not supported so far.
Your best option is to develop it by yourself.
I try to give you a roadmap.
For example, you could give the "type" parameter the special value "textarea". Then, you must add an "else if"... block to create the textarea here:

https://github.com/KasperOlesen/DataTable-AltEditor/blob/4150b2fd78b2ed87612ceb74e4ec700a8a5e04c8/src/dataTables.altEditor.free.js#L535

Moreover, you must send to the server not only the "input" fields but also the "textarea" fields. So, you must modify all the points that filters for ":input" elements, such as here:

https://github.com/KasperOlesen/DataTable-AltEditor/blob/4150b2fd78b2ed87612ceb74e4ec700a8a5e04c8/src/dataTables.altEditor.free.js#L613

**Comment by luca-vercelli** [comment]
Any news on this?

**Comment by goalguy10** [comment]
Might possibly have added support for textareas. I submitted a pull request (https://github.com/KasperOlesen/DataTable-AltEditor/pull/80)
