### ISSUE TITLE
Edit and delete links instead of buttons

### ISSUE THREAD

**Issue by levimatheri** [KasperOlesen/DataTable-AltEditor#77]
It would be nice to have the option to add Edit/Delete links on each row. Similar to [this](https://editor.datatables.net/examples/simple/inTableControls.html). That would give the developer the flexibility of reducing the number of clicks for users.

**Comment by luca-vercelli** [comment]
A (partial) result can be achieved adding a new column with HTML stuff.

```
 {
    name: "action",
    render: function (data, type, row, meta) {
        //may select row number meta.row
      return '<a onclick="$(this).parent().trigger(\'click\');myTable.button(\'edit:name\').trigger(\'click\');">Edit</a> ' +
        '<a onclick="$(this).parent().trigger(\'click\');myTable.button(\'delete:name\').trigger(\'click\');">Delete</a>';
    },
    disabled: true
  }
```

This is ugly to see, but it seems to work (I didn't test carrefully).

**Comment by luca-vercelli** [comment]
Please see https://luca-vercelli.github.io/DataTable-AltEditor/example/12_inline_buttons/example12.html

**Comment by levimatheri** [comment]
@luca-vercelli Thank you. I decided to go with [datatables Editor](https://editor.datatables.net/) since I was on a tight deadline but this looks really good. Could you have an Edit button next to the delete? Currently the edit shows up when a row is selected, I don't know if that's desirable...

**Comment by luca-vercelli** [comment]
@levimatheri yes, that's just an example, an "edit" button can be created just like the "delete" one.
