### ISSUE TITLE
Upload column for an image?

### ISSUE THREAD

**Issue by rpelletierrefocus** [KasperOlesen/DataTable-AltEditor#78]
I am looking to do this: https://editor.datatables.net/examples/advanced/upload.html with the image column. I do not see any examples for how to do this with this library, unless I am mistaken. I would appreciate any assistance to work this out, if possible. Thank you.

**Comment by luca-vercelli** [comment]
No, there is nothing as such.
However, the "type" colum option allows any HTML value, so you could try to set type="file" and see what happens.

**Comment by luca-vercelli** [comment]
any news on this?

**Comment by rpelletierrefocus** [comment]
No, I have not had time to circle back around to it. I will report back when I do.

**Comment by luca-vercelli** [comment]
Related to issues #84 and #88

**Comment by luca-vercelli** [comment]
see the new example n. 10
