### ISSUE TITLE
how to show server side error ? 

### ISSUE THREAD

**Issue by nauman22** [KasperOlesen/DataTable-AltEditor#79]
let suppose we have some checks which needs to be checked on server side validation ... how to show that errors ?

**Comment by luca-vercelli** [comment]
Some error handling is already there. If the server responds with a non-200 HTTP status code, the error should be displayed (I didn't test recently). The function `_errorCallback()` is triggered, and the field `response.status` should be displayed to the user.

**Comment by nauman22** [comment]
thank you for your kind reply
I will manage it using custom success function. 
We really appreciate your work.
God Bless You.
