### ISSUE TITLE
Editing returns datatables error

### ISSUE THREAD

**Issue by Cookiezzz** [KasperOlesen/DataTable-AltEditor#81]
Hi there,

I'm trying to use this plugin into my datatables, but when editing I receive an error.
The data updates fine in the database.
When the success function runs, I get the following in the console.
![image](https://user-images.githubusercontent.com/2996654/75816548-b405a300-5d95-11ea-9a6b-8d474ea97e0c.png)

And the following on screen.
![image](https://user-images.githubusercontent.com/2996654/75816569-bec03800-5d95-11ea-95c7-dfb001fe4b71.png)

Below the JSON I have my php file return to the Ajax call.
![image](https://user-images.githubusercontent.com/2996654/75816705-fa5b0200-5d95-11ea-9b73-3b4926de17b9.png)

I've read the datatables errorpage and I believe this is because I don't have a columndefinition for the 'undefined' row and the 'editRowBtn' rows. But I can't add those since they're not actual columns.

Anyone knows how to get around this or where I went wrong?

JS code.
https://pastebin.com/cJ7bZzjP

**Comment by luca-vercelli** [comment]
Maybe this is a problem with DataTable, not with AltEditor. Did you try setting the `dataSrc `property?

https://datatables.net/reference/option/ajax.dataSrc

In your case it should be `dataSrc=""` I think.

**Comment by luca-vercelli** [comment]
any news? can this issue be closed?
