### ISSUE TITLE
Table reverts to page 1 on edit

### ISSUE THREAD

**Issue by mcrossley** [KasperOlesen/DataTable-AltEditor#82]
I have this working for Ajax edit and delete. But for both functions the datatable refreshes back to page 1 afterwards. If I edit something on page 1, the table is correctly updated with the server response.

It's a bit annoying when you are on say page 178 and make an edit and it reverts back to page 1.

Is this something I have failed to implement, or just how it behaves?

**Comment by luca-vercelli** [comment]
Currently, the editor just behave that way. You did not failed anything.

I think the point is the `draw()` method at this line:
https://github.com/KasperOlesen/DataTable-AltEditor/blob/dd2b19e6ce00f669eebd794b020dddddd9b8bc1e/src/dataTables.altEditor.free.js#L715

I just looked at the Datatable documentation https://datatables.net/reference/api/draw(), it says it is possible to pass a "paging" parameter to set the current page to be display. However some work is needed to do that.

**Comment by mcrossley** [comment]
Great, thanks I changed it to 
`this.s.dt.draw('page'); `

And it refeshes the current table page. 👍

**Comment by luca-vercelli** [comment]
Good.

Could you please submit a PR?

Does it work for both Delete and Edit?

**Comment by mcrossley** [comment]
I am not currently using Delete so have not tested it.

Looking at the documentation the option 'full-hold' may be a better general
use-case than 'page'?

'page' is fine for me because I make the indexed fields read-only, and do
not allow sorting by other fields. If people have sorted the table and edit
the fields selected for sorting, then 'page' will not recalculate the sort.
Maybe this would be better as a user setting value for altEditor?

I'm afraid I have not made a fork - just copied the src code - so cannot
make a PR at the moment.
