### ISSUE TITLE
Hi is there any option to browse image 

### ISSUE THREAD

**Issue by nauman22** [KasperOlesen/DataTable-AltEditor#84]
Hi, its perfect to start with this plugin, Now i want to know about the browse image facility in this plugin?
![Annotation 2020-03-14 104503](https://user-images.githubusercontent.com/17940709/76675968-ea86bd80-65e0-11ea-90dc-a23ad946686a.png)

**Comment by luca-vercelli** [comment]
No "browse image facility" so far.
