### ISSUE TITLE
Compatibility with Jquery 3.x and Bootstrap 4.x?

### ISSUE THREAD

**Issue by morpheus65535** [KasperOlesen/DataTable-AltEditor#85]
I'm trying to use this nice package with Jquery 3.2.0 and Bootstrap 4.3.1. When I click on Add, Edit or Remove, I get the darker backdrop that show but not the modal. Any idea what I'm doing wrong?

**Comment by luca-vercelli** [comment]
Can you provide some js fiddle?

**Comment by morpheus65535** [comment]
No sorry, I had to move to something else to deliver in time. I finally made my own Add, Edit and Remove modal. Sorry.
