### ISSUE TITLE
need image or file upload on field :( please

### ISSUE THREAD

**Issue by inihaekal** [KasperOlesen/DataTable-AltEditor#88]
Hi , 

Thank you so much for the script,can you guys tell me how to upload image ?

**Comment by luca-vercelli** [comment]
I'm afraid this is not supported so far. You can specify "file" as column
type, however I don't know what will happen when the data is sent to server.

Il dom 29 mar 2020, 20:14 inihaekal <notifications@github.com> ha scritto:

**Comment by luca-vercelli** [comment]
Btw, of you have time to investigate what I wrote before, maybe we can find
a solution.

Il dom 29 mar 2020, 20:14 inihaekal <notifications@github.com> ha scritto:

**Comment by inihaekal** [comment]
they have this one https://download.csdn.net/download/qq_21336651/10847238
@luca-vercelli, but i dont have account for this website.

**Comment by luca-vercelli** [comment]
Something was done (see example n.10).
