### ISSUE TITLE
Currency support

### ISSUE THREAD

**Issue by seunets** [KasperOlesen/DataTable-AltEditor#89]
Hi guys!

I'm willing to add currency support but can't figure out a plugin to use.

Any thoughts?

**Comment by luca-vercelli** [comment]
Are you talking about the AltEditor? Or this is a general question on Datatable's ? You should better ask on [their forum](https://datatables.net/forums/).

**Comment by seunets** [comment]
No it's about AltEditor. I'm planning to add support to currency fields.

**Comment by luca-vercelli** [comment]
I cannot imagine what support you are thinking of.
A currency is just a number. I think values should be stored as numbers, and you can pretty-render them on the Datatable via some custom render() function.

**Comment by seunets** [comment]
You're right but Datatables prior to 1.10 had a columnDefs currency type, so I thought using this property to allow localized input masks for AltEditor.
