### ISSUE TITLE
Edit, Add, and Delete buttons event handling

### ISSUE THREAD

**Issue by wuthmone** [KasperOlesen/DataTable-AltEditor#9]
Hi! How to handle the events of edit, add, and delete? I need to make some API calls when each button is clicked like "PUT", "POST", and "DELETE" respectively. Can you help me where to add the code for those event handling? I have tried something like as follows but it didn't work. "editRowBtn" is the ID of Submit button in edit modal. 

$('#editRowBtn').click(function(e){
			$.ajax({
			url: "api3.php",
			dataType: "json",
			type:"POST",
			data: {
				appType:$('#APP_TYPE').val(),
				capacity:$('#CAP').val(),
				mesRate:$('#MEPS_RATE').val(),
				capUnit:"hpower",
				deflt:$('#DEFAULT').val(),
				ref:$('#REF').val(),
				calBase:$('#CAL_BASE').val(),
				
				type:"baselineData"
			},
			error: function(jqxhr,textStatus,errorThrown){
				
				alert('Error retrieving informations!...');
				console.log (jqxhr.status);
				console.log (textStatus);
				console.log (errorThrown);
			},
  		    beforeSend: function(){
				
				//$('#gifImg').html('loading');

			},
			success: function(baselineObj){
				console.log("edit success!");
				
			}//success
			});//ajax
			
		});// function

**Comment by zack-hable** [comment]
Not sure if you're still looking for this functionality, but I've added support for user specified functions on table rows being added/edited/deleted in [my fork](https://github.com/zack-hable/DataTable-AltEditor)

**Comment by luca-vercelli** [comment]
Hello @zack-hable , I finally tried out your code. The new functionality is interesting, however your code breaks a number of use cases. If I am not wrong, all the 3 examples I did in the past do not work anymore: you *must* have an AJAX source of data configured to make your code work. Without it, there is no way to edit data. I think this is a bit too much.

**Comment by luca-vercelli** [comment]
Ok, I got the problem. You always refresh the datatable, after each operation. If there is not a backend configured, this will fail. I am going to work on this.
