### ISSUE TITLE
Is it possible to send form data along with the url for Alt-editor AJAX call

### ISSUE THREAD

**Issue by ersanir** [KasperOlesen/DataTable-AltEditor#92]

**Comment by luca-vercelli** [comment]
I am not sure I understand your question. Do you want to send data via GET instead than POST? You can handle that by yourself inside the AJAX call that you provide.

**Comment by ersanir** [comment]
I have a form in my page of type enctype="multipart/form-data" and it has a file attachment. I was wondering if I could serialize the forms data and pass to the backend servlet . I am currently passing it like this. It is not convenient if my form has more fields or if I want to pass the file as well

ajax: {
           url: '/fda/intranet/translationNew/TranslationFileServ?' + '&choice=' + choice + '&language=' 
          + language,
          type: 'POST'
          },

**Comment by luca-vercelli** [comment]
I think you are using the wrong method.
The GET method is intended for sending parameters via URL.
The POST method is intended for sending parameters via request body.
The $.ajax command will behave in different ways if you use GET or POST:

    $.ajax({url:'https://example.com', method:'POST', data: {choice:'1', language:'it' }})

will send parameters in request body,

    $.ajax({url:'https://example.com', method:'GET' data: {choice:'1', language:'it' }})

will send parameters in URL query.

**Comment by ersanir** [comment]
Got it . Thank you
