### ISSUE TITLE
Ajax + AltEditor not working as it should

### ISSUE THREAD

**Issue by Rdago** [KasperOlesen/DataTable-AltEditor#93]
Hello, 

First thanks for the Alteditor! 

I´m havin some issues passing with AJAX Data, maybe you have an idea: 

My Datatable: 

```
  $('#WorkoutTable').DataTable({
        "sPaginationType": "full_numbers",
        "processing": true,
        "serverSide": true,
         ajax: {
            url: 'api/training/get',
            dataSrc: ''
        },
        columns: [
                    {
                    data: "id",
                    title: "Id",
                    type: "readonly"
                },
                    { 
                        "data": "name",
                    "title": "Name" 
                    },
                    { 
                        "data": "dtm",
                        "title": "Datum" 
                    },
                ],
        dom: 'Bfrtip',        // Needs button container
        select: 'single',
        responsive: true,
        altEditor: true,     // Enable altEditor
        buttons: [{
        text: 'add',
        name: 'add'        // do not change name
        },
        {
        extend: 'selected', // Bind to Selected row
        text: 'edit',
        name: 'edit'        // do not change name
        },
        {
        extend: 'selected', // Bind to Selected row
        text: 'delete',
        name: 'delete'      // do not change name
        }],
        onEditRow: function(datatable, rowdata, success, error) {
            $.ajax({
                url: "api/training/update",
                type: 'POST',
                data: JSON.stringify(rowdata),
                success: success,
                error: error
            });
        }
	     
      } );
```

Getting the Data displayed is not an issue, that works fine.  Is there a way I can get the "id" of the row, without showing it in the Datatable? If I take it out of the columns, I can´t send it to modify my entriess. 

Getting the Data from AJAX Call makes my Table look a bit weird: 
![image](https://user-images.githubusercontent.com/62183866/79695961-15b49a80-827a-11ea-95e1-ad4a17bf496f.png)

This 6 Rows is the whole content of the AJAX call but its displaying 0 out of 0 and like unlimited pages. 

EDIT: 
I had the wrong JS-library imported, editing works now. Data is still showing weird.

I dont get how the Succes / Error works. I have "message" in my json output can I print it on "Edit Record"- Modal ? 
Why am I getting this Warning?? 
"DataTables warning: table id=WorkoutTable - Requested unknown parameter 'id' for row 2, column 0. For more information about this error, please see http://datatables.net/tn/4"

I Hope you can help me fixxing this. :)

**Comment by luca-vercelli** [comment]
"Showing 0 of 0 entries (...)" is given (IMHO) by the server-side processing. The Datatable needs to know the total number of rows. I have never used server-side processing so far, so I can't help you. If you really have 6 rows only, you should better disable it.

The warning "DataTables warning: table id=WorkoutTable - Requested unknown parameter 'id" is very common. It is saying that the Datatable cannot find the column "id" in the received data. Usually it means that data is in a wrong format. When a row is added/edited, the webservice should return the line just updated, so that the Datatable can redraw it.

For error messages you can look this: https://github.com/KasperOlesen/DataTable-AltEditor/issues/79

**Comment by Rdago** [comment]
Thanks for the answer, got it working. 

Still have 1 Issue left. How can I get the ID without actually showing it in the table? it is not in "rowdata" when I delete the Column wird ID.

**Comment by luca-vercelli** [comment]
Ok, I see that you found by yourself the solution to your questions.

I don't know what you mean with

> modify the Modal opening

When the modal dialog is opened an event is triggered (`alteditor:some_dialog_opened`, `alteditor:add_dialog_opened `and similar ones), you may use them.

**Comment by mmmcorpsvit** [comment]
> 
> 
> Ok, I see that you found by yourself the solution to your questions.
> 
> I don't know what you mean with
> 
> > modify the Modal opening
> 
> When the modal dialog is opened an event is triggered (`alteditor:some_dialog_opened`, `alteditor:add_dialog_opened `and similar ones), you may use them.

can share any sample please for triggers?
can't understand how use
