### ISSUE TITLE
Column not sorting if type:"textarea"

### ISSUE THREAD

**Issue by ersanir** [KasperOlesen/DataTable-AltEditor#94]
My jquery datatable editor column is defined like this:

{title: "en_us", data: "en_us", type: "textarea", width: '20%'}

I want the column to be both readonly and of type textarea. How can I achieve this ?

Also, I noticed that the column 'en_us' is sortable if I use type:"readonly" but if I use type:"textarea", the column sort is not working.

**Comment by luca-vercelli** [comment]
You are right, the "textarea" type does not support most of the properties supported by "input" fields. If you compare the lines https://github.com/KasperOlesen/DataTable-AltEditor/blob/d0f3e538c80e7a33d06e4204a774036a3dc239db/src/dataTables.altEditor.free.js#L565 and https://github.com/KasperOlesen/DataTable-AltEditor/blob/d0f3e538c80e7a33d06e4204a774036a3dc239db/src/dataTables.altEditor.free.js#L574 you shall see that the "textarea" piece of code lacks a lot of properties. You may try to add them.

If you do that, please consider submitting a PR.

**Comment by luca-vercelli** [comment]
Should be fixed.
