### ISSUE TITLE
Avoiding column wrap to next line

### ISSUE THREAD

**Issue by ersanir** [KasperOlesen/DataTable-AltEditor#95]
![datatable](https://user-images.githubusercontent.com/17056055/79891470-06933100-83cf-11ea-9fcd-248410a96a9b.PNG)

I do not want the final column in my datatable to wrap over to the next line. How can I achieve this. I have tried setting column width in percentages as well as fixed width. I can still see the green '+'
in my row

**Comment by luca-vercelli** [comment]
This is a question about Datatables, not AltEditor. You should better ask on [their forum](https://datatables.net/forums/).
