### ISSUE TITLE
select2  placeholder: "Select a state", allowClear: true

### ISSUE THREAD

**Issue by aaronyeo40** [KasperOlesen/DataTable-AltEditor#96]
How do I place the placeholder and allowclear for select2?

**Comment by luca-vercelli** [comment]
It seems that the placeholder works for text input
https://github.com/KasperOlesen/DataTable-AltEditor/blob/cf703648313cdf5c43b8813a125b453d6aa405f7/src/dataTables.altEditor.free.js#L579 but not for selects:
https://github.com/KasperOlesen/DataTable-AltEditor/blob/cf703648313cdf5c43b8813a125b453d6aa405f7/src/dataTables.altEditor.free.js#L552
maybe you can modify the "<select>" part?

**Comment by luca-vercelli** [comment]
should be fixed
