### ISSUE TITLE
multi editorOnChange 

### ISSUE THREAD

**Issue by aaronyeo40** [KasperOlesen/DataTable-AltEditor#97]
How do i implement multi editorOnChange ?

                    {
                        data: "Division",
                        title: "Division",
                        type: "select",
                        options: divArrayData,
                        select2: { width: "100%" },
                        editorOnChange: function (event, altEditor) {
                            console.log(event, altEditor);
                            var dpl = $(event.currentTarget).val();
                            $('#TRANCODE').val(dpl);
                        },
                    },
                    {
                        data: "CC",
                        title: "CCC",
                        type: "select",
                        options: divArrayDataCC,
                        select2: { width: "100%" },
                        editorOnChange: function (event, altEditor) {
                            console.log(event, altEditor);
                            var dplcc = $(event.currentTarget).val();
                            $('#TRANCODECC').val(dplcc);
                        },
                    },

**Comment by luca-vercelli** [comment]
Maybe you are talking about dependent select menus? Did you see [this example](https://luca-vercelli.github.io/DataTable-AltEditor/example/07_dependent_select/example7.html) ?

**Comment by aaronyeo40** [comment]
I saw it. When I try to implement more than one editorOnChange it will always take effect in the last one. I pass division value to trancode but the result going to date plant

here is my code

          {
                data: "Division",
                title: "Division",
                type: "select",
                options: divArrayData,
                select2: { width: "100%" },
                editorOnChange: function (event, altEditor) {
                    var dpla = $(event.currentTarget).val();
                    $('#TRANCODE').val(dpla);
                }
            },
            {
                data: "TRANCODE",
                title: "Trancode",
                type: "search"
            },
            {
                data: "Date_Planted",
                title: "Date Plant",
                datetimepicker: { timepicker: false, format: "d/m/Y" },
                editorOnChange: function (event, altEditor) { alert("b")
                    var dpl = $(event.currentTarget).val();
                    var characters = dpl.substr(0, 6);
                    var charactersL = dpl.substr(6, 10);
                    var fesr = parseInt(charactersL) + 25;
                    var wwe = characters + fesr;
                    $('#Date_Replant').val(wwe);
                }
            },

![asd](https://user-images.githubusercontent.com/64132454/80287396-fb8c2800-8763-11ea-9ff1-9c3b45be0bc4.jpg)

**Comment by elrondcouncil** [comment]
change this source code
if (columnDefs[j].editorOnChange) {
           var f = columnDefs[j].editorOnChange; // FIXME what if more than 1 editorOnChange ?   
          $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).on('change', function(elm) {
                            f(elm, that);
                        });
            }
with this 

if (columnDefs[j].editorOnChange) {
        $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).attr('alt-editor-id', this._quoteattr(j));
         $(selector).find("#" + $.escapeSelector(columnDefs[j].name)).on('change', function(elm) {
                           let f= columnDefs[$(this).attr('alt-editor-id')].editorOnChange;
                            f(elm, that);
                        });
 }

**Comment by luca-vercelli** [comment]
@elrondcouncil that looks a good idea. Would you mind to push a PR? (using `var` instead of `let`, I suggest).
